---
title: "Chapter 14. Stan"
author: "A Solomon Kurz"
date: "`r format(Sys.Date())`"
output:
  github_document
---

# Stan

> Stan is the name of a software package that creates representative samples of parameter values from a posterior distribution for complex hierarchical models, analogous to JAGS...
> 
> According to the Stan reference manual, Stan is named after Stanislaw Ulam (1909-1984), who was a pioneer of Monte Carlo methods. (Stan is not named after the slang term referring to an overenthusiastic or psychotic fanatic, formed by a combination of the words "stalker" and "fan.") The name of the software package has also been unpacked as the acronym, Sampling Through Adaptive Neighborhoods ([Gelman et al., 2013, p. 307](http://www.stat.columbia.edu/~gelman/book/)), but it is usually written as Stan not STAN.
>
> Stan uses a different method than JAGS for generating Monte Carlo steps. The method is called *Hamiltonian Monte Carlo* (HMC). HMC can be more effective than the various samplers in JAGS and BUGS, especially for large complex models. Moreover, Stan operates with compiled C++ and allows greater programming flexibility, which again is especially useful for unusual or complex models. For large data sets or complex models, Stan can provide solutions when JAGS (or BUGS) takes too long or fails. (pp. 399--400, *emphasis* in the original)

To learn more about Stan from the Stan team themselves, check out the main website [https://mc-stan.org/](https://mc-stan.org/). If you'e like to dive deep, bookmark the [Stan User's Guide](https://mc-stan.org/docs/2_21/stan-users-guide/index.html) and the [Stan Language Reference Manual](https://mc-stan.org/docs/2_21/reference-manual/index.html). We won't be using Stan directly in this project, preferring to interface with it indirectly through the interface of Bürkner's **brms** package. If you haven't already, book mark the **brms** [GitHub repository](https://github.com/paul-buerkner/brms), [CRAN page](https://cran.r-project.org/web/packages/brms/index.html), and [reference manual](https://cran.r-project.org/web/packages/brms/brms.pdf). You can also view Bürkner talk about it in his talk from the useR! International R User 2017 Conference, [*brms: Bayesian Multilevel Models using Stan*](https://www.youtube.com/watch?v=40o0_0XTB6E).

## HMC sampling

I will flesh out the rest of the content for this chapter in later editions of this project.

## References {-}

Kruschke, J. K. (2015). *Doing Bayesian data analysis, Second Edition: A tutorial with R, JAGS, and Stan.* Burlington, MA: Academic Press/Elsevier.

## Session info {-}

```{r}
sessionInfo()
```

