project:
  type: book

book:
  title: "*Doing Bayesian Data Analysis* in brms and the tidyverse"
  subtitle: "version 1.3.0"
  author: A. Solomon Kurz
  date: now
  favicon: dogs_favicon.png
  search: true
  repo-url: https://github.com/ASKurz/Doing-Bayesian-Data-Analysis-in-brms-and-the-tidyverse
  repo-actions: issue
  chapters:
    - index.qmd
    - 01.qmd
    - part: part_01.qmd
      chapters:
        - 02.qmd
        - 03.qmd
        - 04.qmd
        - 05.qmd
    - part: part_02.qmd
      chapters:
        - 06.qmd
        - 07.qmd
        - 08.qmd
        - 09.qmd
        - 10.qmd
        - 11.qmd
        - 12.qmd
        - 13.qmd
        - 14.qmd
    - part: part_03.qmd
      chapters:
        - 15.qmd
        - 16.qmd
        - 17.qmd
        - 18.qmd
        - 19.qmd
        - 20.qmd
        - 21.qmd
        - 22.qmd
        - 23.qmd
        - 24.qmd
        - 25.qmd
    - references.qmd    

toc: true
toc-depth: 5

bibliography: bib_zotero.bib
biblio-style: apalike
csl: apa.csl
link-citations: true

format:
  html:
    theme: cosmo
    code-copy: true

engine: knitr
knitr:
  opts_chunk: 
    R.options:
      width: 130  # https://github.com/quarto-dev/quarto-cli/discussions/3934

editor: source

number-sections: true

comments:
  giscus:
    repo: ASKurz/Doing-Bayesian-Data-Analysis-in-brms-and-the-tidyverse

highlight-style: github

