


# Metric Predicted Variable with Multiple Metric Predictors

> We will consider models in which the predicted variable is an additive combination of predictors, all of which have proportional influence on the prediction. This kind of model is called *multiple linear regression*. We will also consider nonadditive combinations of predictors, which are called *interactions*. [@kruschkeDoingBayesianData2015, p. 509, *emphasis* in the original]

## Multiple linear regression

Say we have one criterion $y$ and two predictors, $x_1$ and $x_2$. If $y \sim \operatorname{Normal}(\mu, \sigma)$ and $\mu = \beta_0 + \beta_1 x_1 + \beta_2 x_2$, then it's also the case that we can rewrite the formula for $y$ as

$$y \sim \operatorname{Normal}(\beta_0 + \beta_1 x_1 + \beta_2 x_2, \sigma).$$

As Kruschke pointed out, the basic model "assumes homogeneity of variance, which means that at all values of $x_1$ and $x_2$, the variance $\sigma^2$ of $y$ is the same" (p. 510).

If we presume the data for the two $x$ variables are uniformly distributed within 0 and 10, we can make the data for Figure 18.1 like this.


```r
library(tidyverse)

n <- 300

set.seed(18)
d <-
  tibble(x_1 = runif(n = n, min = 0, max = 10),
         x_2 = runif(n = n, min = 0, max = 10)) %>% 
  mutate(y = rnorm(n = n, mean = 10 + x_1 + 2 * x_2, sd = 1))

head(d)  
```

```
## # A tibble: 6 x 3
##     x_1   x_2     y
##   <dbl> <dbl> <dbl>
## 1 8.23   8.62  36.9
## 2 7.10   1.33  20.3
## 3 9.66   1.08  19.5
## 4 0.786  7.09  25.1
## 5 0.536  6.67  25.6
## 6 5.75   4.72  25.7
```

Before we plot those `d` data, we'll want to make a data object containing the information necessary to make the grid lines for Kruschke's 3D regression plane. To my mind, this will be easier to do in stages. If you look at the top upper panel of Figure 18.1 as a reference, our first step will be to make the vertical lines. Save them as `d1`.


```r
theme_set(
  theme_linedraw() +
    theme(panel.grid = element_blank())
)

d1 <-
  tibble(index = 1:21,
         x_1   = seq(from = 0, to = 10, length.out = 21)) %>% 
  expand(nesting(index, x_1),
         x_2 = c(0, 10)) %>% 
  mutate(y = 10 + 1 * x_1 + 2 * x_2)

d1 %>% 
  ggplot(aes(x = x_1, y = y, group = index)) +
  geom_path(color = "grey85") +
  ylim(0, 50)
```

<img src="18_files/figure-html/unnamed-chunk-3-1.png" width="336" style="display: block; margin: auto;" />

You may have noticed our `theme_set()` lines at the top. Though we'll be using a different default theme later in the project, this is the best theme to use for these initial few plots. Okay, now let's make the more horizontally-oriented grid lines and save them as `d2`.


```r
d2 <-
  tibble(index = 1:21 + 21,
         x_2   = seq(from = 0, to = 10, length.out = 21)) %>% 
  expand(nesting(index, x_2),
         x_1 = c(0, 10)) %>% 
  mutate(y = 10 + 1 * x_1 + 2 * x_2)

d2 %>% 
  ggplot(aes(x = x_1, y = y, group = index)) +
  geom_path(color = "grey85") +
  ylim(0, 50)
```

<img src="18_files/figure-html/unnamed-chunk-4-1.png" width="336" style="display: block; margin: auto;" />

Now combine the two and save them as `grid`.


```r
grid <-
  bind_rows(d1, d2) 

grid %>%
  ggplot(aes(x = x_1, y = y, group = index)) +
  geom_path(color = "grey85") +
  ylim(0, 50)
```

<img src="18_files/figure-html/unnamed-chunk-5-1.png" width="336" style="display: block; margin: auto;" />

```r
grid %>%
  ggplot(aes(x = x_2, y = y, group = index)) +
  geom_path(color = "grey85") +
  ylim(0, 50)
```

<img src="18_files/figure-html/unnamed-chunk-5-2.png" width="336" style="display: block; margin: auto;" />

```r
grid %>%
  ggplot(aes(x = x_1, y = x_2, group = index)) +
  geom_path(color = "grey85")
```

<img src="18_files/figure-html/unnamed-chunk-5-3.png" width="336" style="display: block; margin: auto;" />

We're finally ready combine `d` and `grid` to make the three 2D scatter plots from Figure 18.1.


```r
d %>% 
  ggplot(aes(x = x_1, y = y)) +
  geom_path(data = grid,
            aes(group = index),
            color = "grey85") +
  geom_point(shape = 21, stroke = 1/10,
             color = "white", fill = "steelblue4") +
  scale_x_continuous(limits = c(0, 10), expand = c(0, 0), breaks = 0:5 * 2) +
  scale_y_continuous(limits = c(0, 50), expand = c(0, 0))
```

<img src="18_files/figure-html/unnamed-chunk-6-1.png" width="336" style="display: block; margin: auto;" />

```r
d %>% 
  ggplot(aes(x = x_2, y = y)) +
  geom_path(data = grid,
            aes(group = index),
            color = "grey85") +
  geom_point(shape = 21, stroke = 1/10,
             color = "white", fill = "steelblue4") +
  scale_x_continuous(limits = c(0, 10), expand = c(0, 0), breaks = 0:5 * 2) +
  scale_y_continuous(limits = c(0, 50), expand = c(0, 0))
```

<img src="18_files/figure-html/unnamed-chunk-6-2.png" width="336" style="display: block; margin: auto;" />

```r
d %>% 
  ggplot(aes(x = x_1, y = x_2)) +
  geom_path(data = grid,
            aes(group = index),
            color = "grey85") +
  geom_point(shape = 21, stroke = 1/10,
             color = "white", fill = "steelblue4") +
  scale_x_continuous(limits = c(0, 10), expand = c(0, 0), breaks = 0:5 * 2) +
  scale_y_continuous(limits = c(0, 10), expand = c(0, 0), breaks = 0:5 * 2)
```

<img src="18_files/figure-html/unnamed-chunk-6-3.png" width="336" style="display: block; margin: auto;" />

As in previous chapters, I'm not aware that **ggplot2** allows for three-dimensional wireframe plots of the kind in the upper left panel. If you'd like to make one in base **R**, have at it.

For Figure 18.2, the $x$ variables look to be multivariate normal with a correlation of about -.95. We can simulate such data with help from the [**MASS** package](https://CRAN.R-project.org/package=MASS) [@R-MASS; @MASS2002].

Sven Hohenstein's [answer to this stats.stackexchange.com question](https://stats.stackexchange.com/questions/164471/generating-a-simulated-dataset-from-a-correlation-matrix-with-means-and-standard) provides the steps for simulating the data. First, we'll need to specify the desired means and standard deviations for our variables. Then we'll make a correlation matrix with 1s on the diagonal and the desired correlation coefficient, $\rho$ on the off-diagonal. Since the correlation matrix is symmetric, both off-diagonal positions are the same. Then we convert the correlation matrix to a covariance matrix.


```r
mus <- c(5, 5)
sds <- c(2, 2)

cors <- matrix(c(1, -.95,
                 -.95, 1), 
               ncol = 2)
cors
```

```
##       [,1]  [,2]
## [1,]  1.00 -0.95
## [2,] -0.95  1.00
```

```r
covs <- sds %*% t(sds) * cors
covs
```

```
##      [,1] [,2]
## [1,]  4.0 -3.8
## [2,] -3.8  4.0
```

Now we've defined our means, standard deviations, and covariance matrix, we're ready to simulate the data with the `MASS::mvrnorm()` function.


```r
# how many data points would you like to simulate?
n <- 300

set.seed(18.2)

d <- 
  MASS::mvrnorm(n = n, 
                mu = mus, 
                Sigma = covs, 
                empirical = T) %>% 
  as_tibble() %>% 
  set_names("x_1", "x_2") %>%  
  mutate(y = rnorm(n = n, mean = 10 + x_1 + 2 * x_2))
```

Now we have our simulated data in hand, we're ready for three of the four panels of Figure 18.2.


```r
p1 <-
  d %>% 
  ggplot(aes(x = x_1, y = y)) +
  geom_path(data = grid,
            aes(group = index),
            color = "grey85") +
  geom_point(shape = 21, stroke = 1/10,
             color = "white", fill = "steelblue4") +
  scale_x_continuous(limits = c(0, 10), expand = c(0, 0), breaks = 0:5 * 2) +
  scale_y_continuous(limits = c(0, 50), expand = c(0, 0))

p2 <-
  d %>% 
  ggplot(aes(x = x_2, y = y)) +
  geom_path(data = grid,
            aes(group = index),
            color = "grey85") +
  geom_point(shape = 21, stroke = 1/10,
             color = "white", fill = "steelblue4") +
  scale_x_continuous(limits = c(0, 10), expand = c(0, 0), breaks = 0:5 * 2) +
  scale_y_continuous(limits = c(0, 50), expand = c(0, 0))

p3 <-
  d %>% 
  ggplot(aes(x = x_1, y = x_2)) +
  geom_path(data = grid,
            aes(group = index),
            color = "grey85") +
  geom_point(shape = 21, stroke = 1/10,
             color = "white", fill = "steelblue4") +
  scale_x_continuous(limits = c(0, 10), expand = c(0, 0), breaks = 0:5 * 2) +
  scale_y_continuous(limits = c(0, 10), expand = c(0, 0), breaks = 0:5 * 2)

# bind them together with patchwork
library(patchwork)

plot_spacer() + p1 + p2 + p3
```

<img src="18_files/figure-html/unnamed-chunk-9-1.png" width="576" style="display: block; margin: auto;" />

We came pretty close.

### The perils of correlated predictors.

> Figures 18.1 and 18.2 show data generated from the same model. In both figures, $\sigma = 2, \beta_0 = 10, \beta_1 = 1, \text{ and } \beta_2 = 2$. All that differs between the two figures is the distribution of the $\langle x_1, x_2 \rangle$ values, which is not specified by the model. In Figure 18.1, the $\langle x_1, x_2 \rangle$ values are distributed independently. In Figure 18.2, the $\langle x_1, x_2 \rangle$ values are negatively correlated: When $x_1$ is small, $x_2$ tends to be large, and when $x_1$ is large, $x_2$ tends to be small. (p. 510)

If you look closely at our simulation code from above, you'll see we have done so, too.

> Real data often have correlated predictors. For example, consider trying to predict a state's average high-school SAT score on the basis of the amount of money the state spends per pupil. If you plot only mean SAT against money spent, there is actually a *decreasing* trend... (p. 513, *emphasis* in the original)

Before we remake Figure 18.3 to examine that decreasing trend, we'll need to load the data from [@guber1999getting].


```r
my_data <- read_csv("data.R/Guber1999data.csv")

glimpse(my_data)
```

```
## Rows: 50
## Columns: 8
## $ State     <chr> "Alabama", "Alaska", "Arizona", "Arkansas", "California", "C…
## $ Spend     <dbl> 4.405, 8.963, 4.778, 4.459, 4.992, 5.443, 8.817, 7.030, 5.71…
## $ StuTeaRat <dbl> 17.2, 17.6, 19.3, 17.1, 24.0, 18.4, 14.4, 16.6, 19.1, 16.3, …
## $ Salary    <dbl> 31.144, 47.951, 32.175, 28.934, 41.078, 34.571, 50.045, 39.0…
## $ PrcntTake <dbl> 8, 47, 27, 6, 45, 29, 81, 68, 48, 65, 57, 15, 13, 58, 5, 9, …
## $ SATV      <dbl> 491, 445, 448, 482, 417, 462, 431, 429, 420, 406, 407, 468, …
## $ SATM      <dbl> 538, 489, 496, 523, 485, 518, 477, 468, 469, 448, 482, 511, …
## $ SATT      <dbl> 1029, 934, 944, 1005, 902, 980, 908, 897, 889, 854, 889, 979…
```

Before we get all excited and try to plot those data as in Figure 18.3, we'll need to redefine the 3D grid of our regression plane, this time based on the equation at the top of Figure 18.3.


```r
d1 <-
  tibble(index = 1:21,
         Spend = seq(from = 3.4, to = 10.1, length.out = 21)) %>% 
  expand(nesting(index, Spend),
         PrcntTake = c(0, 85))

d2 <-
  tibble(index     = 1:21 + 21,
         PrcntTake = seq(from = 0, to = 85, length.out = 21)) %>% 
  expand(nesting(index, PrcntTake),
         Spend = c(3.4, 10.1))

grid <-
  bind_rows(d1, d2) %>% 
  mutate(SATT = 993.8 + -2.9 * PrcntTake + 12.3 * Spend)

grid %>% glimpse()
```

```
## Rows: 84
## Columns: 4
## $ index     <dbl> 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9, 10, 10…
## $ Spend     <dbl> 3.400, 3.400, 3.735, 3.735, 4.070, 4.070, 4.405, 4.405, 4.74…
## $ PrcntTake <dbl> 0, 85, 0, 85, 0, 85, 0, 85, 0, 85, 0, 85, 0, 85, 0, 85, 0, 8…
## $ SATT      <dbl> 1035.6200, 789.1200, 1039.7405, 793.2405, 1043.8610, 797.361…
```

Now we have our updated `grid` object, we're ready to plot the data in our version of Figure 18.3.


```r
p1 <-
  my_data %>% 
  ggplot(aes(x = Spend, y = SATT)) +
  geom_path(data = grid,
            aes(group = index),
            color = "grey85") +
  geom_point(shape = 21, stroke = 1/10,
             color = "white", fill = "steelblue4") +
  scale_x_continuous(limits = c(3.4, 10.1), expand = c(0, 0), breaks = 2:5 * 2) +
  scale_y_continuous(limits = c(785, 1120))

p2 <-
  my_data %>% 
  ggplot(aes(x = PrcntTake, y = SATT)) +
  geom_path(data = grid,
            aes(group = index),
            color = "grey85") +
  geom_point(shape = 21, stroke = 1/10,
             color = "white", fill = "steelblue4") +
  scale_x_continuous("% Take", limits = c(0, 85), expand = c(0, 0)) +
  scale_y_continuous(limits = c(785, 1120))

p3 <-
  my_data %>% 
  ggplot(aes(x = PrcntTake, y = Spend)) +
  geom_path(data = grid,
            aes(group = index),
            color = "grey85") +
  geom_point(shape = 21, stroke = 1/10,
             color = "white", fill = "steelblue4") +
  scale_x_continuous("% Take", limits = c(0, 85), expand = c(0, 0)) +
  scale_y_continuous(limits = c(3.4, 10.1), expand = c(0, 0))

# bind them together and add a title
wrap_elements(grid::textGrob('No 3D wireframe plots for us')) + 
  p1 + p2 + p3 + 
  plot_annotation(title = "SATT ~ N(m,sd=31.5), m = 993.8 + −2.9 %Take + 12.3 Spend")
```

<img src="18_files/figure-html/unnamed-chunk-12-1.png" width="576" style="display: block; margin: auto;" />

You can learn more about how we added that title to our plot ensemble from Pedersen's [-@Pedersen2020AddingAnnotation] vignette, [*Adding annotation and style*](https://patchwork.data-imaginist.com/articles/guides/annotation.html), and more about how we added that text in place of a wireframe plot from another of his [-@Pedersen2020PlotAssembly] vignettes, [*Plot assembly*](https://patchwork.data-imaginist.com/articles/guides/assembly.html).

> The separate influences of the two predictors could be assessed in this example because the predictors had only mild correlation with each other. There was enough independent variation of the two predictors that their distinct relationships to the outcome variable could be detected. In some situations, however, the predictors are so tightly correlated that their distinct effects are difficult to tease apart. Correlation of predictors causes the estimates of their regression coefficients to trade-off, as we will see when we examine the posterior distribution. (p. 514)

### The model and implementation.

Let's make our version of the model diagram in Figure 18.4 to get a sense of where we're going. If you look back to [Section 17.2][Robust linear regression], you'll see this is just a minor reworking of the code from Figure 17.2.


```r
# normal density
p1 <-
  tibble(x = seq(from = -3, to = 3, by = .1)) %>% 
  ggplot(aes(x = x, y = (dnorm(x)) / max(dnorm(x)))) +
  geom_area(fill = "steelblue4", color = "steelblue4", alpha = .6) +
  annotate(geom = "text",
           x = 0, y = .2,
           label = "normal",
           size = 7) +
  annotate(geom = "text",
           x = c(0, 1.5), y = .6,
           label = c("italic(M)[0]", "italic(S)[0]"), 
           size = 7, family = "Times", parse = T) +
  scale_x_continuous(expand = c(0, 0)) +
  theme_void() +
  theme(axis.line.x = element_line(size = 0.5))

# a second normal density
p2 <-
  tibble(x = seq(from = -3, to = 3, by = .1)) %>% 
  ggplot(aes(x = x, y = (dnorm(x)) / max(dnorm(x)))) +
  geom_area(fill = "steelblue4", color = "steelblue4", alpha = .6) +
  annotate(geom = "text",
           x = 0, y = .2,
           label = "normal",
           size = 7) +
  annotate(geom = "text",
           x = c(0, 1.5), y = .6,
           label = c("italic(M)[italic(j)]", "italic(S)[italic(j)]"), 
           size = 7, family = "Times", parse = T) +
  scale_x_continuous(expand = c(0, 0)) +
  theme_void() +
  theme(axis.line.x = element_line(size = 0.5))

## two annotated arrows
# save our custom arrow settings
my_arrow <- arrow(angle = 20, length = unit(0.35, "cm"), type = "closed")
p3 <-
  tibble(x    = c(.33, 1.67),
         y    = c(1, 1),
         xend = c(.67, 1.2),
         yend = c(0, 0)) %>%
  
  ggplot(aes(x = x, xend = xend,
             y = y, yend = yend)) +
  geom_segment(arrow = my_arrow) +
  annotate(geom = "text",
           x = c(.35, 1.3), y = .5,
           label = "'~'",
           size = 10, family = "Times", parse = T) +
  xlim(0, 2) +
  theme_void()

# exponential density
p4 <-
  tibble(x = seq(from = 0, to = 1, by = .01)) %>% 
  ggplot(aes(x = x, y = (dexp(x, 2) / max(dexp(x, 2))))) +
  geom_area(fill = "steelblue4", color = "steelblue4", alpha = .6) +
  annotate(geom = "text",
           x = .5, y = .2,
           label = "exp",
           size = 7) +
  annotate(geom = "text",
           x = .5, y = .6,
           label = "italic(K)",
           size = 7, family = "Times", parse = T) +
  scale_x_continuous(expand = c(0, 0)) +
  theme_void() +
  theme(axis.line.x = element_line(size = 0.5))

# likelihood formula
p5 <-
  tibble(x = .5,
         y = .25,
         label = "beta[0]+sum()[italic(j)]*beta[italic(j)]*italic(x)[italic(ji)]") %>% 
  
  ggplot(aes(x = x, y = y, label = label)) +
  geom_text(size = 7, parse = T, family = "Times") +
  scale_x_continuous(expand = c(0, 0), limits = c(0, 1)) +
  ylim(0, 1) +
  theme_void()
  
  # half-normal density
p6 <-
  tibble(x = seq(from = 0, to = 3, by = .01)) %>% 
  ggplot(aes(x = x, y = (dnorm(x)) / max(dnorm(x)))) +
  geom_area(fill = "steelblue4", color = "steelblue4", alpha = .6) +
  annotate(geom = "text",
           x = 1.5, y = .2,
           label = "half-normal",
           size = 7) +
  annotate(geom = "text",
           x = 1.5, y = .6,
           label = "0*','*~italic(S)[sigma]", 
           size = 7, family = "Times", parse = T) +
  scale_x_continuous(expand = c(0, 0)) +
  theme_void() +
  theme(axis.line.x = element_line(size = 0.5))

# four annotated arrows
p7 <-
  tibble(x    = c(.43, .43, 1.5, 2.5),
         y    = c(1, .55, 1, 1),
         xend = c(.43, 1.225, 1.5, 1.75),
         yend = c(.8, .15, .2, .2)) %>%
  
  ggplot(aes(x = x, xend = xend,
             y = y, yend = yend)) +
  geom_segment(arrow = my_arrow) +
  annotate(geom = "text",
           x = c(.3, .7, 1.38, 2), y = c(.92, .22, .65, .6),
           label = c("'~'", "'='", "'='", "'~'"),
           size = 10, family = "Times", parse = T) +
  annotate(geom = "text",
           x = .43, y = .7,
           label = "nu*minute+1",
           size = 7, family = "Times", parse = T) +
  xlim(0, 3) +
  theme_void()

# student-t density
p8 <-
  tibble(x = seq(from = -3, to = 3, by = .1)) %>% 
  ggplot(aes(x = x, y = (dt(x, 3) / max(dt(x, 3))))) +
  geom_area(fill = "steelblue4", color = "steelblue4", alpha = .6) +
  annotate(geom = "text",
           x = 0, y = .2,
           label = "student t",
           size = 7) +
  annotate(geom = "text",
           x = 0, y = .6,
           label = "nu~~~mu[italic(i)]~~~sigma",
           size = 7, family = "Times", parse = T) +
  scale_x_continuous(expand = c(0, 0)) +
  theme_void() +
  theme(axis.line.x = element_line(size = 0.5))

# the final annotated arrow
p9 <-
  tibble(x     = c(.375, .625),
         y     = c(1/3, 1/3),
         label = c("'~'", "italic(i)")) %>% 
  
  ggplot(aes(x = x, y = y, label = label)) +
  geom_text(size = c(10, 7), parse = T, family = "Times") +
  geom_segment(x = .5, xend = .5,
               y = 1, yend = 0, 
               arrow = my_arrow) +
  xlim(0, 1) +
  theme_void()

# some text
p10 <-
  tibble(x     = .5,
         y     = .5,
         label = "italic(y[i])") %>% 
  
  ggplot(aes(x = x, y = y, label = label)) +
  geom_text(size = 7, parse = T, family = "Times") +
  xlim(0, 1) +
  theme_void()

# define the layout
layout <- c(
  area(t = 1, b = 2, l = 3, r = 5),
  area(t = 1, b = 2, l = 7, r = 9),
  area(t = 4, b = 5, l = 1, r = 3),
  area(t = 4, b = 5, l = 5, r = 7),
  area(t = 4, b = 5, l = 9, r = 11),
  area(t = 3, b = 4, l = 3, r = 9),
  area(t = 7, b = 8, l = 5, r = 7),
  area(t = 6, b = 7, l = 1, r = 11),
  area(t = 9, b = 9, l = 5, r = 7),
  area(t = 10, b = 10, l = 5, r = 7)
)

# combine and plot!
(p1 + p2 + p4 + p5 + p6 + p3 + p8 + p7 + p9 + p10) + 
  plot_layout(design = layout) &
  ylim(0, 1) &
  theme(plot.margin = margin(0, 5.5, 0, 5.5))
```

<img src="18_files/figure-html/unnamed-chunk-13-1.png" width="648" style="display: block; margin: auto;" />

"As with the model for simple linear regression, the Markov Chain Monte Carlo (MCMC) sampling can be more efficient if the data are mean-centered or standardized" (p. 515). We'll make a custom function to standardize the criterion and predictor values.


```r
standardize <- function(x) {
  (x - mean(x)) / sd(x)
}

my_data <-
  my_data %>% 
  mutate(prcnt_take_z = standardize(PrcntTake),
         spend_z      = standardize(Spend),
         satt_z       = standardize(SATT))
```

Let's open **brms**.


```r
library(brms)
```

Now we're ready to fit the model. As Kruschke pointed out, the priors on the standardized predictors are set with

> an arbitrary standard deviation of 2.0. This value was chosen because standardized regression coefficients are algebraically constrained to fall between −1 and +1 in least-squares regression, [[^5]] and therefore, the regression coefficients will not exceed those limits by much. A normal distribution with standard deviation of 2.0 is reasonably flat over the range from −1 to +1. (p. 516)

With data like this, even a `prior(normal(0, 1), class = b)` would be only mildly regularizing.

This is a good place to emphasize how priors in **brms** are given classes. If you'd like all parameters within a given class to have the prior, you can just specify one prior argument within that class. For our `fit8.1`, both parameters of `class = b` have a `normal(0, 2)` prior. So we can just include one statement to handle both. Had we wanted different priors for the coefficients for `spend_z` and `prcnt_take_z`, we'd need to include two `prior()` arguments with at least one including a `coef` argument.


```r
fit18.1 <-
  brm(data = my_data,
      family = student,
      satt_z ~ 1 + spend_z + prcnt_take_z,
      prior = c(prior(normal(0, 2), class = Intercept),
                prior(normal(0, 2), class = b),
                prior(normal(0, 1), class = sigma),
                prior(exponential(one_over_twentynine), class = nu)),
      chains = 4, cores = 4,
      stanvars = stanvar(1/29, name = "one_over_twentynine"),
      seed = 18,
      file = "fits/fit18.01")
```

Check the model summary.


```r
print(fit18.1)
```

```
##  Family: student 
##   Links: mu = identity; sigma = identity; nu = identity 
## Formula: satt_z ~ 1 + spend_z + prcnt_take_z 
##    Data: my_data (Number of observations: 50) 
## Samples: 4 chains, each with iter = 2000; warmup = 1000; thin = 1;
##          total post-warmup samples = 4000
## 
## Population-Level Effects: 
##              Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
## Intercept       -0.00      0.06    -0.12     0.13 1.00     4372     2732
## spend_z          0.23      0.08     0.08     0.39 1.00     3297     2815
## prcnt_take_z    -1.03      0.08    -1.18    -0.88 1.00     3145     2706
## 
## Family Specific Parameters: 
##       Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
## sigma     0.42      0.05     0.32     0.53 1.00     3040     2444
## nu       33.14     28.97     4.32   110.75 1.00     3263     2441
## 
## Samples were drawn using sampling(NUTS). For each parameter, Bulk_ESS
## and Tail_ESS are effective sample size measures, and Rhat is the potential
## scale reduction factor on split chains (at convergence, Rhat = 1).
```

So when we use a multivariable model, increases in spending now appear associated with *increases* in SAT scores.

### The posterior distribution.

Based on Equation 18.1, we can convert the standardized coefficients from our multivariable model back to their original metric as follows:

\begin{align*}
\beta_0 & = \operatorname{SD}_y \zeta_0 + M_y - \operatorname{SD}_y \sum_j \frac{\zeta_j M_{x_j}}{\operatorname{SD}_{x_j}} \;\;\; \text{and} \\
\beta_j & = \frac{\operatorname{SD}_y \zeta_j}{\operatorname{SD}_{x_j}}.
\end{align*}

To use them, we'll first extract the posterior samples.


```r
post <- posterior_samples(fit18.1)

head(post)
```

```
##   b_Intercept  b_spend_z b_prcnt_take_z     sigma        nu      lp__
## 1 -0.07012038 0.27740012     -1.0568377 0.4507400 25.119802 -35.96155
## 2  0.05064683 0.22718315     -0.9942048 0.3694775  9.591157 -36.12758
## 3  0.01395296 0.20918474     -1.0727454 0.3893164 16.662585 -35.52875
## 4  0.02425840 0.07386948     -0.7951866 0.4142515 45.138087 -39.57061
## 5 -0.03452118 0.30533030     -1.0695329 0.4702354 21.662401 -36.25199
## 6 -0.04914289 0.35406349     -1.1300740 0.4795296 31.350165 -37.20342
```

Like we did in [Chapter 17][Metric Predicted Variable with One Metric Predictor], let's wrap the consequences of Equation 18.1 into two functions.


```r
make_beta_0 <- function(zeta_0, zeta_1, zeta_2, sd_x_1, sd_x_2, sd_y, m_x_1, m_x_2, m_y) {
  sd_y * zeta_0 + m_y - sd_y * ((zeta_1 * m_x_1 / sd_x_1) + (zeta_2 * m_x_2 / sd_x_2))
}

make_beta_j <- function(zeta_j, sd_j, sd_y) {
  sd_y * zeta_j / sd_j
}
```

After saving a few values, we're ready to use our custom functions.


```r
sd_x_1 <- sd(my_data$Spend)
sd_x_2 <- sd(my_data$PrcntTake)
sd_y   <- sd(my_data$SATT)
m_x_1  <- mean(my_data$Spend)
m_x_2  <- mean(my_data$PrcntTake)
m_y    <- mean(my_data$SATT)

post <-
  post %>% 
  mutate(b_0 = make_beta_0(zeta_0 = b_Intercept,
                           zeta_1 = b_spend_z,
                           zeta_2 = b_prcnt_take_z,
                           sd_x_1 = sd_x_1,
                           sd_x_2 = sd_x_2,
                           sd_y   = sd_y,
                           m_x_1  = m_x_1,
                           m_x_2  = m_x_2,
                           m_y    = m_y),
         b_1 = make_beta_j(zeta_j = b_spend_z,
                           sd_j   = sd_x_1,
                           sd_y   = sd_y),
         b_2 = make_beta_j(zeta_j = b_prcnt_take_z,
                           sd_j   = sd_x_2,
                           sd_y   = sd_y))

glimpse(post)
```

```
## Rows: 4,000
## Columns: 9
## $ b_Intercept    <dbl> -0.0701203816, 0.0506468330, 0.0139529589, 0.0242583997…
## $ b_spend_z      <dbl> 0.27740012, 0.22718315, 0.20918474, 0.07386948, 0.30533…
## $ b_prcnt_take_z <dbl> -1.0568377, -0.9942048, -1.0727454, -0.7951866, -1.0695…
## $ sigma          <dbl> 0.4507400, 0.3694775, 0.3893164, 0.4142515, 0.4702354, …
## $ nu             <dbl> 25.119802, 9.591157, 16.662585, 45.138087, 21.662401, 3…
## $ lp__           <dbl> -35.96155, -36.12758, -35.52875, -39.57061, -36.25199, …
## $ b_0            <dbl> 974.8591, 994.0051, 1004.8329, 1022.1289, 969.7182, 958…
## $ b_1            <dbl> 15.229771, 12.472768, 11.484623, 4.055569, 16.763189, 1…
## $ b_2            <dbl> -2.954635, -2.779531, -2.999109, -2.223129, -2.990128, …
```

Before we make the figure, we'll update our overall plot theme to `cowplot::theme_minimal_grid()`. Our overall color scheme and plot aesthetic will be based on some of the plots in [Chapter 16, *Visualizing uncertainty*](https://clauswilke.com/dataviz/visualizing-uncertainty.html), of @wilkeFundamentalsDataVisualization2019. As we'll be making a lot of customized density plots in this chapter, we may as well cave those settings, here. We'll call the function with those settings `stat_wilke()`.


```r
library(tidybayes)
library(ggdist)
library(cowplot)

# update the default theme setting
theme_set(theme_minimal_grid())

# define the function
stat_wilke <- function(height = 1.25, point_size = 5, ...) {
  
  list(
    # for the graded fill
    stat_slab(aes(fill_ramp = stat(
      cut_cdf_qi(cdf, 
                 .width = c(.8, .95, .99),
                 labels = scales::percent_format(accuracy = 1)))), 
      height = height, slab_alpha = .75, fill = "steelblue4", 
      ...),
    # for the top outline and the mode dot
    stat_halfeye(.width = 0, point_interval = mode_qi,
                 height = height, size = point_size, slab_size = 1/3,
                 slab_color = "steelblue4", fill = NA, color = "chocolate3", 
                 ...),
    # fill settings
    scale_fill_ramp_discrete(range = c(1, .4), na.translate = F),
    # adjust the guide_legend() settings
    guides(fill_ramp = 
             guide_legend(
               direction = "horizontal",
               keywidth = unit(0.925, "cm"),
               label.hjust = 0.5,
               label.position = "bottom",
               title = "posterior prob.",
               title.hjust = 0.5,
               title.position = "top")),
    # ensure we're using `cowplot::theme_minimal_hgrid()` as a base theme
    theme_minimal_hgrid(),
    # adjust the legend settings
    theme(legend.background = element_rect(fill = "white"),
          legend.text = element_text(margin = margin(-0.2, 0, -0.2, 0, "cm")),
          legend.title = element_text(margin = margin(-0.2, 0, -0.2, 0, "cm")))
  )
  
}
```



Here's the top panel of Figure 18.5.


```r
# here are the primary data
post %>% 
  transmute(Intercept      = b_0,
            Spend          = b_1,
            `Percent Take` = b_2,
            Scale          = sigma * sd_y,
            Normality      = nu %>% log10()) %>% 
  gather() %>% 
  
  # the plot
  ggplot(aes(x = value)) +
  stat_wilke(normalize = "panels") +
  scale_y_continuous(NULL, breaks = NULL) +
  xlab(NULL) +
  coord_cartesian(ylim = c(-0.01, NA)) +
  panel_border() +
  theme(legend.position = c(.72, .2)) +
  facet_wrap(~ key, scales = "free", ncol = 3)
```

<img src="18_files/figure-html/unnamed-chunk-22-1.png" width="576" style="display: block; margin: auto;" />

> The slope on spending has a mode of about 13, which suggests that SAT scores rise by about 13 points for every extra $1000 spent per pupil. The slope on percentage taking the exam (PrcntTake) is also credibly non-zero, with a mode around −2.8, which suggests that SAT scores fall by about 2.8 points for every additional 1% of students who take the test. (p. 517)

If you want those exact modes and, say, 50% intervals around them, you can just use `tidybayes::mode_hdi()`.


```r
post %>% 
  transmute(Spend          = b_1,
            `Percent Take` = b_2) %>% 
  gather() %>% 
  group_by(key) %>% 
  mode_hdi(value, .width = .5)
```

```
## # A tibble: 2 x 7
##   key          value .lower .upper .width .point .interval
##   <chr>        <dbl>  <dbl>  <dbl>  <dbl> <chr>  <chr>    
## 1 Percent Take -2.89  -3.00  -2.71    0.5 mode   hdi      
## 2 Spend        13.3    9.42  15.1     0.5 mode   hdi
```

The `brms::bayes_R2()` function makes it easy to compute a Bayesian $R^2$. Simply feed a `brm()` fit object into `bayes_R2()` and you'll get back the posterior mean, $SD$, and 95% intervals.


```r
bayes_R2(fit18.1)
```

```
##     Estimate  Est.Error      Q2.5    Q97.5
## R2 0.8139515 0.02291166 0.7566704 0.842708
```

I'm not going to go into the technical details here, but you should be aware that the Bayeisan $R^2$ returned from the `bayes_R2()` function is not calculated the same as it is with OLS. If you want to dive in, check out the paper by @gelmanRsquaredBayesianRegression2019, [*R-squared for Bayesian regression models*](https://stat.columbia.edu/~gelman/research/published/bayes_R2_v3.pdf). Anyway, if you'd like to view the Bayesian $R^2$ distribution rather than just get the summaries, specify `summary = F`, convert the output to a tibble, and plot as usual.


```r
bayes_R2(fit18.1, summary = F) %>% 
  as_tibble() %>% 
  
  ggplot(aes(x = R2, y = 0)) +
  stat_wilke() +
  scale_y_continuous(NULL, breaks = NULL) +
  labs(subtitle = expression(paste("Bayesian ", italic(R)^2)),
       x = NULL) +
  coord_cartesian(xlim = c(0, 1),
                  ylim = c(-0.01, NA)) +
  theme(legend.position = c(.01, .8))
```

<img src="18_files/figure-html/unnamed-chunk-25-1.png" width="336" style="display: block; margin: auto;" />

Since the `brms::bayes_R2()` function is not identical with Kruschke's method in the text, the results might differ a bit.

We can get a sense of the scatter plots with `bayesplot::mcmc_pairs()`.


```r
library(bayesplot)

color_scheme_set(c("steelblue4", "steelblue4", "steelblue4", "steelblue4", "steelblue4", "steelblue4"))

post %>% 
  transmute(Intercept      = b_0,
            Spend          = b_1,
            `Percent Take` = b_2,
            Scale          = sigma * sd_y,
            Normality      = nu %>% log10()) %>% 
  mcmc_pairs(diag_fun = "dens",
             off_diag_args = list(size = 1/8, alpha = 1/8))
```

<img src="18_files/figure-html/unnamed-chunk-26-1.png" width="576" style="display: block; margin: auto;" />

One way to get the Pearson's correlation coefficients among the parameters is with `psych::lowerCor()`.


```r
post %>% 
  transmute(Intercept      = b_0,
            Spend          = b_1,
            `Percent Take` = b_2,
            Scale          = sigma * sd_y,
            Normality      = nu %>% log10()) %>% 
  psych::lowerCor(digits = 3)
```

```
##              Intrc  Spend  PrcnT  Scale  Nrmlt 
## Intercept     1.000                            
## Spend        -0.937  1.000                     
## Percent Take  0.320 -0.584  1.000              
## Scale         0.071 -0.075  0.058  1.000       
## Normality     0.076 -0.097  0.112  0.327  1.000
```

If you like more control for customizing your pairs plots, you'll find a friend in the `ggpairs()` function from the [**GGally** package](https://cran.r-project.org/package=GGally) [@R-GGally]. We're going to blow past the default settings and customize the format for the plots in the upper triangle, the diagonal, and the lower triangle.


```r
library(GGally)

my_upper <- function(data, mapping, ...) {
  ggplot(data = data, mapping = mapping) + 
    geom_point(size = 1/2, shape = 21, stroke = 1/10,
               color = "white", fill = "steelblue4") +
    panel_border()
}

my_diag <- function(data, mapping, ...) {
  ggplot(data = data, mapping = mapping) + 
    stat_wilke(point_size = 2) +
    scale_x_continuous(NULL, breaks = NULL) +
    scale_y_continuous(NULL, breaks = NULL) +
    coord_cartesian(ylim = c(-0.01, NA)) +
    panel_border()
}

my_lower <- function(data, mapping, ...) {
  
  # get the x and y data to use the other code
  x <- eval_data_col(data, mapping$x)
  y <- eval_data_col(data, mapping$y)
  
  # compute the correlations
  corr <- cor(x, y, method = "p", use = "pairwise")
  
  # plot the cor value
  ggally_text(
    label = formatC(corr, digits = 2, format = "f") %>% str_replace(., "0\\.", "."),
    mapping = aes(),
    color = "black",
    size = 4) +
    scale_x_continuous(NULL, breaks = NULL) +
    scale_y_continuous(NULL, breaks = NULL) +
    panel_border()
}
```

Let's see what we've done.


```r
post %>% 
  transmute(`Intercept~(beta[0])`    = b_0,
            `Spend~(beta[1])`        = b_1,
            `Percent~Take~(beta[2])` = b_2,
            sigma                    = sigma * sd_y,
            `log10(nu)`              = nu %>% log10()) %>% 
  ggpairs(upper = list(continuous = my_upper),
          diag  = list(continuous = my_diag),
          lower = list(continuous = my_lower),
          labeller = label_parsed) +
  theme(strip.text = element_text(size = 8))
```

<img src="18_files/figure-html/unnamed-chunk-29-1.png" width="576" style="display: block; margin: auto;" />

For more ideas on customizing a `ggpairs()` plot, go [here](https://ggobi.github.io/ggally/articles/ggpairs.html) or [here](https://stackoverflow.com/questions/30858337/how-to-customize-lines-in-ggpairs-ggally) or [here](https://stackoverflow.com/questions/45873483/ggpairs-plot-with-heatmap-of-correlation-values).

Kruschke finished the subsection with the observation: "Sometimes we are interested in using the linear model to predict $y$ values for $x$ values of interest. It is straight forward to generate a large sample of credible $y$ values for specified $x$ values" (p. 519).

Like we practiced with in the last chapter, the simplest way to do so in **brms** is with the `fitted()` function. For a quick example, say we wanted to know what the model would predict if we were to have a standard-score increase in spending and a simultaneous standard-score decrease in the percent taking the exam. We'd just specify those values in a tibble and feed that tibble into `fitted()` along with the model.


```r
nd <-
  tibble(prcnt_take_z = -1,
         spend_z      =  1)

fitted(fit18.1,
       newdata = nd)
```

```
##      Estimate Est.Error      Q2.5    Q97.5
## [1,] 1.262859  0.153978 0.9558164 1.569301
```

### Redundant predictors.

> As a simplified example of correlated predictors, think of just two data points: Suppose $y = 1 \text{ for }  \langle x_1, x_2 \rangle = \langle 1, 1 \rangle \text{ and } y = 2 \text{ for } \langle x_1, x_2 \rangle = \langle 2, 2 \rangle$. The linear model, $y = \beta_1 x_1 + \beta_2 x_2$ is supposed to satisfy both data points, and in this case both are satisfied by $1 = \beta_1 + \beta_2$. Therefore, many different combinations of $\beta_1$ and $\beta_2$ satisfy the data. For example, it could be that $\beta_1 = 2$ and $\beta_2 = -1$, or $\beta_1 = 0.5$ and $\beta_2 = 0.5$, or $\beta_1 = 0$ and $\beta_2 = 1$. In other words, the credible values of $\beta_1$ and $\beta_2$ are anticorrelated and trade-off to fit the data. (p. 519)

Here are what those data look like. You would not want to fit a regression model with these data.


```r
tibble(x_1 = 1:2,
       x_2 = 1:2,
       y   = 1:2)
```

```
## # A tibble: 2 x 3
##     x_1   x_2     y
##   <int> <int> <int>
## 1     1     1     1
## 2     2     2     2
```

We can take percentages and turn them into their inverse re-expressed as a proportion.


```r
percent_take <- 37

(100 - percent_take) / 100
```

```
## [1] 0.63
```

Let's make a redundant predictor and then `standardize()` it.


```r
my_data <-
  my_data %>% 
  mutate(prop_not_take   = (100 - PrcntTake) / 100) %>% 
  mutate(prop_not_take_z = standardize(prop_not_take))
  
glimpse(my_data)
```

```
## Rows: 50
## Columns: 13
## $ State           <chr> "Alabama", "Alaska", "Arizona", "Arkansas", "Californi…
## $ Spend           <dbl> 4.405, 8.963, 4.778, 4.459, 4.992, 5.443, 8.817, 7.030…
## $ StuTeaRat       <dbl> 17.2, 17.6, 19.3, 17.1, 24.0, 18.4, 14.4, 16.6, 19.1, …
## $ Salary          <dbl> 31.144, 47.951, 32.175, 28.934, 41.078, 34.571, 50.045…
## $ PrcntTake       <dbl> 8, 47, 27, 6, 45, 29, 81, 68, 48, 65, 57, 15, 13, 58, …
## $ SATV            <dbl> 491, 445, 448, 482, 417, 462, 431, 429, 420, 406, 407,…
## $ SATM            <dbl> 538, 489, 496, 523, 485, 518, 477, 468, 469, 448, 482,…
## $ SATT            <dbl> 1029, 934, 944, 1005, 902, 980, 908, 897, 889, 854, 88…
## $ prcnt_take_z    <dbl> -1.0178453, 0.4394222, -0.3078945, -1.0925770, 0.36469…
## $ spend_z         <dbl> -1.10086058, 2.24370805, -0.82716069, -1.06123647, -0.…
## $ satt_z          <dbl> 0.8430838, -0.4266207, -0.2929676, 0.5223163, -0.85431…
## $ prop_not_take   <dbl> 0.92, 0.53, 0.73, 0.94, 0.55, 0.71, 0.19, 0.32, 0.52, …
## $ prop_not_take_z <dbl> 1.0178453, -0.4394222, 0.3078945, 1.0925770, -0.364690…
```

We're ready to fit the redundant-predictor model.


```r
fit18.2 <-
  brm(data = my_data,
      family = student,
      satt_z ~ 0 + Intercept + spend_z + prcnt_take_z + prop_not_take_z,
      prior = c(prior(normal(0, 2), class = b, coef = "Intercept"),
                prior(normal(0, 2), class = b, coef = "spend_z"),
                prior(normal(0, 2), class = b, coef = "prcnt_take_z"),
                prior(normal(0, 2), class = b, coef = "prop_not_take_z"),
                prior(normal(0, 1), class = sigma),
                prior(exponential(one_over_twentynine), class = nu)),
      chains = 4, cores = 4,
      stanvars = stanvar(1/29, name = "one_over_twentynine"),
      seed = 18,
      # this will let us use `prior_samples()` later on
      sample_prior = "yes",
      file = "fits/fit18.02")
```

You might notice a few things about the `brm()` code. First, we have used the `~ 0 + Intercept + ...` syntax instead of the default syntax for intercepts. In normal situations, we would have been in good shape using the typical `~ 1 + ...` syntax for the intercept, especially given our use of standardized data. However, since **brms** version 2.5.0, using the `sample_prior` argument to draw samples from the prior distribution will no longer allow us to return samples from the typical **brms** intercept. Bürkner addressed the issue on the [Stan forums](https://discourse.mc-stan.org/t/prior-intercept-samples-no-longer-saved-in-brms-2-5-0/6107). As he pointed out, if you want to get prior samples from an intercept, you'll have to use the alternative syntax. The other thing to point out is that even though we used the same prior on all the predictors, including the intercept, we still explicitly spelled each out with the `coef` argument. If we hadn't been explicit like this, we would only get a single `b` vector from the `prior_samples()` function. But since we want separate vectors for each of our predictors, we used the verbose code. If you're having a difficult time understanding these two points, experiment. Fit the model in a few different ways with either the typical or the alternative intercept syntax and with either the verbose prior code or the simplified `prior(normal(0, 2), class = b)` code. And after each, execute `prior_samples(fit18.2)`. You'll see.

Let's move on. Kruschke mentioned high autocorrelations in the prose. Here are the autocorrelation plots for our $\beta$'s.


```r
color_scheme_set(c("steelblue4", "steelblue4", "chocolate3", "steelblue4", "steelblue4", "steelblue4"))

post <- posterior_samples(fit18.2, add_chain = T)

mcmc_acf(post, 
         pars = c("b_Intercept", "b_spend_z", "b_prcnt_take_z", "b_prop_not_take_z"), 
         lags = 10)
```

<img src="18_files/figure-html/unnamed-chunk-34-1.png" width="624" style="display: block; margin: auto;" />

Looks like HMC made a big difference. The $N_{eff}/N$ ratios weren't terrible, either.


```r
color_scheme_set(c("steelblue4", "steelblue4", "chocolate3", "steelblue4", "chocolate3", "chocolate3"))

neff_ratio(fit18.2)[1:6] %>% 
  mcmc_neff() +
  yaxis_text(hjust = 0)
```

<img src="18_files/figure-html/unnamed-chunk-35-1.png" width="576" style="display: block; margin: auto;" />

The `brms::vcov()` function returns a variance/covariance matrix--or a correlation matrix when you set `correlation = T`--of the population-level parameters (i.e., the fixed effects). It returns the values to a decadent level of precision, so we'll simplify the output with `round()`.


```r
vcov(fit18.2, correlation = T) %>% 
  round(digits = 3)
```

```
##                 Intercept spend_z prcnt_take_z prop_not_take_z
## Intercept           1.000  -0.040       -0.001          -0.002
## spend_z            -0.040   1.000        0.016           0.050
## prcnt_take_z       -0.001   0.016        1.000           0.998
## prop_not_take_z    -0.002   0.050        0.998           1.000
```

Notice how much lower our `Spend_z` correlations are than those Kruschke displayed on page 520 of the text. However, it turns out the correlations among the redundant predictors were still very high.

> If any of the nondiagonal correlations are high (i.e., close to +1 or close to −1), be careful when interpreting the posterior distribution. Here, we can see that the correlation of PrcntTake and PropNotTake is −1.0, which is an immediate sign of redundant predictors. (p. 520)

You can really get a sense of the silliness of the parameters if you plot them. We'll use `stat_wilke()` to get a sense of densities and summaries of the $\beta$'s.


```r
post %>% 
  select(b_Intercept:b_prop_not_take_z) %>% 
  gather() %>% 
  # this line isn't necessary, but it does allow us to arrange the parameters on the y-axis
  mutate(key = factor(key, levels = c("b_prop_not_take_z", "b_prcnt_take_z", "b_spend_z", "b_Intercept"))) %>% 
  
  ggplot(aes(x = value, y = key)) +
  geom_vline(xintercept = 0, color = "white") +
  stat_wilke(normalize = "xy", point_size = 3) +
  labs(x = NULL, 
       y = NULL) +
  coord_cartesian(xlim = c(-5, 5),
                  ylim = c(1.4, NA)) +
  theme(axis.text.y = element_text(hjust = 0),
        legend.position = c(.76, .8))
```

<img src="18_files/figure-html/unnamed-chunk-37-1.png" width="768" style="display: block; margin: auto;" />

Yeah, on the standardized scale those are some ridiculous estimates. Let's update our `make_beta_0()` function.


```r
make_beta_0 <- function(zeta_0, zeta_1, zeta_2, zeta_3, sd_x_1, sd_x_2, sd_x_3, sd_y, m_x_1, m_x_2, m_x_3,  m_y) {
  sd_y * zeta_0 + m_y - sd_y * ((zeta_1 * m_x_1 / sd_x_1) + (zeta_2 * m_x_2 / sd_x_2) + (zeta_3 * m_x_3 / sd_x_3))
}
```


```r
sd_x_1 <- sd(my_data$Spend)
sd_x_2 <- sd(my_data$PrcntTake)
sd_x_3 <- sd(my_data$prop_not_take)
sd_y   <- sd(my_data$SATT)
m_x_1  <- mean(my_data$Spend)
m_x_2  <- mean(my_data$PrcntTake)
m_x_3  <- mean(my_data$prop_not_take)
m_y    <- mean(my_data$SATT)

post <-
  post %>% 
  transmute(Intercept = make_beta_0(zeta_0 = b_Intercept,
                                    zeta_1 = b_spend_z,
                                    zeta_2 = b_prcnt_take_z,
                                    zeta_3 = b_prop_not_take_z,
                                    sd_x_1 = sd_x_1,
                                    sd_x_2 = sd_x_2,
                                    sd_x_3 = sd_x_3,
                                    sd_y   = sd_y,
                                    m_x_1  = m_x_1,
                                    m_x_2  = m_x_2,
                                    m_x_3  = m_x_3,
                                    m_y    = m_y),
            Spend = make_beta_j(zeta_j = b_spend_z,
                                sd_j   = sd_x_1,
                                sd_y   = sd_y),
            `Percent Take` = make_beta_j(zeta_j = b_prcnt_take_z,
                                         sd_j   = sd_x_2,
                                         sd_y   = sd_y),
            `Proportion not Take` = make_beta_j(zeta_j = b_prop_not_take_z,
                                                sd_j   = sd_x_3,
                                                sd_y   = sd_y),
            Scale     = sigma * sd_y,
            Normality = nu %>% log10())

glimpse(post)
```

```
## Rows: 4,000
## Columns: 6
## $ Intercept             <dbl> 1665.1918, 1665.9205, 1631.1347, 749.1133, 1559.…
## $ Spend                 <dbl> 10.829312, 13.908710, 16.273287, 13.139030, 11.9…
## $ `Percent Take`        <dbl> -9.3160321, -9.5376112, -9.8313823, -0.7766573, …
## $ `Proportion not Take` <dbl> -666.816554, -684.499897, -640.918882, 250.36445…
## $ Scale                 <dbl> 33.98042, 32.81935, 33.73075, 29.59968, 35.68761…
## $ Normality             <dbl> 2.2238759, 1.3988676, 1.6364214, 1.1598285, 1.65…
```

Now we've done the conversions, here are the histograms of Figure 18.6.


```r
post %>% 
  gather() %>% 
  
  ggplot(aes(x = value, y = 0)) +
  stat_wilke(normalize = "panels") +
  scale_y_continuous(NULL, breaks = NULL) +
  xlab(NULL) +
  coord_cartesian(ylim = c(-0.01, NA)) +
  panel_border() +
  theme(axis.text.x = element_text(size = 8),
        legend.position = "none") +
  facet_wrap(~ key, scales = "free", ncol = 3)
```

<img src="18_files/figure-html/unnamed-chunk-40-1.png" width="576" style="display: block; margin: auto;" />

Their scatter plots are as follows.


```r
post %>% 
  set_names("Intercept~(beta[0])", "Spend~(beta[1])", "Percent~Take~(beta[2])", "Percent~Not~Take~(beta[3])", "sigma", "log10(nu)") %>% 
  ggpairs(upper = list(continuous = my_upper),
          diag = list(continuous = my_diag),
          lower = list(continuous = my_lower),
          labeller = label_parsed) +
  theme(strip.text = element_text(size = 7))
```

<img src="18_files/figure-html/unnamed-chunk-41-1.png" width="672" style="display: block; margin: auto;" />

Figure 18.7 is all about the prior predictive distribution. Here we'll extract the priors with `prior_samples()` and wrangle all in one step.


```r
prior <- 
  prior_samples(fit18.2) %>% 
  transmute(Intercept = make_beta_0(zeta_0 = b_Intercept,
                                    zeta_1 = b_spend_z,
                                    zeta_2 = b_prcnt_take_z,
                                    zeta_3 = b_prop_not_take_z,
                                    sd_x_1 = sd_x_1,
                                    sd_x_2 = sd_x_2,
                                    sd_x_3 = sd_x_3,
                                    sd_y   = sd_y,
                                    m_x_1  = m_x_1,
                                    m_x_2  = m_x_2,
                                    m_x_3  = m_x_3,
                                    m_y    = m_y),
            Spend = make_beta_j(zeta_j = b_spend_z,
                                sd_j   = sd_x_1,
                                sd_y   = sd_y),
            `Percent Take` = make_beta_j(zeta_j = b_prcnt_take_z,
                                         sd_j   = sd_x_2,
                                         sd_y   = sd_y),
            `Proportion not Take` = make_beta_j(zeta_j = b_prop_not_take_z,
                                                sd_j   = sd_x_3,
                                                sd_y   = sd_y),
            Scale     = sigma * sd_y,
            Normality = nu %>% log10()) 

glimpse(prior)
```

```
## Rows: 4,000
## Columns: 6
## $ Intercept             <dbl> 1180.9992, -423.4836, 517.1341, 1012.5929, 415.9…
## $ Spend                 <dbl> -1.872029, 29.301555, 99.280635, -44.364768, 88.…
## $ `Percent Take`        <dbl> 7.3776439, 5.2245469, 0.6089012, -1.2181105, 3.3…
## $ `Proportion not Take` <dbl> -340.15333, 1524.12211, 129.76334, 444.33940, 10…
## $ Scale                 <dbl> 57.563345, 93.749738, 10.696817, 13.638205, 49.0…
## $ Normality             <dbl> 1.1801271, 1.4448769, 0.7727354, 0.9946487, 1.20…
```

Now we've wrangled the priors, we're ready to make the histograms at the top of Figure 18.7.


```r
prior %>% 
  gather() %>% 
  
  ggplot(aes(x = value, y = 0)) +
  stat_wilke(normalize = "panels") +
  scale_y_continuous(NULL, breaks = NULL) +
  xlab(NULL) +
  coord_cartesian(ylim = c(-0.01, NA)) +
  panel_border() +
  theme(axis.text.x = element_text(size = 8),
        legend.position = "none") +
  facet_wrap(~ key, scales = "free", ncol = 3)
```

<img src="18_files/figure-html/unnamed-chunk-43-1.png" width="576" style="display: block; margin: auto;" />

Since we used the half-Gaussian prior for our $\sigma$, our `Scale` histogram looks different from Kruschke's. Otherwise, everything's on the up and up. Here are the pairs plots at the bottom of Figure 18.7.


```r
prior %>% 
  set_names("Intercept~(beta[0])", "Spend~(beta[1])", "Percent~Take~(beta[2])", "Percent~Not~Take~(beta[3])", "sigma", "log10(nu)") %>% 
  ggpairs(upper = list(continuous = my_upper),
          diag = list(continuous = my_diag),
          lower = list(continuous = my_lower),
          labeller = label_parsed) +
  theme(strip.text = element_text(size = 7))
```

<img src="18_files/figure-html/unnamed-chunk-44-1.png" width="672" style="display: block; margin: auto;" />

At the top of page 523, Kruschke asked us to "notice that the posterior distribution in Figure 18.6 has ranges for the redundant parameters that are only a little smaller than their priors." With a little wrangling, we can compare the prior/posterior distributions for our redundant parameters more directly.


```r
post %>% 
  gather(parameter, posterior) %>% 
  bind_cols(
    prior %>%
      gather() %>% 
      transmute(prior = value)
    ) %>% 
  gather(key, value, -parameter) %>% 
  
  filter(parameter %in% c("Percent Take", "Proportion not Take")) %>% 
  
  ggplot(aes(x = value, y = 0)) +
  stat_wilke(normalize = "panels") +
  scale_fill_viridis_d(option = "D", begin = .35, end = .65) +
  scale_y_continuous(NULL, breaks = NULL) +
  xlab(NULL) +
  coord_cartesian(ylim = c(-0.01, NA)) +
  panel_border() +
  theme(legend.position = "none") +
  facet_grid(key ~ parameter, scales = "free")
```

<img src="18_files/figure-html/unnamed-chunk-45-1.png" width="576" style="display: block; margin: auto;" />

Kruschke was right. The posterior distributions are only slightly narrower than the priors for those two. With our combination of data and model, we learned virtually nothing beyond the knowledge we encoded in those priors.

Kruschke mentioned SEM as a possible solution to multicollinearity. **brms** isn't fully capable of SEM, at the moment (see [issue #304](https://github.com/paul-buerkner/brms/issues/304)), but its [multivariate syntax](https://CRAN.R-project.org/package=brms/vignettes/brms_multivariate.html) [@Bürkner2021Multivariate] does allow for [path analysis](http://www.imachordata.com/2017/12/21/bayesian-sem-with-brms/) and [IRT models](https://github.com/paul-buerkner/brms/issues/203). However, you can currently fit a variety of Bayesian SEMs with the [**blavaan** package](https://CRAN.R-project.org/package=blavaan) [@Merkle2018blavaan; @R-blavaan]. I'm not aware of any textbooks highlighting **blavaan**. If you know of any, [please share](https://github.com/ASKurz/Doing-Bayesian-Data-Analysis-in-brms-and-the-tidyverse/issues).

### Informative priors, sparse data, and correlated predictors.

It's worth reproducing some of Kruschke's prose from this subsection.

> The examples in this book tend to use mildly informed priors (e.g., using information about the rough magnitude and range of the data). But a benefit of Bayesian analysis is the potential for cumulative scientific progress by using priors that have been informed from previous research.
>
> Informed priors can be especially useful when the amount of data is small compared to the parameter space. A strongly informed prior essentially reduces the scope of the credible parameter space, so that a small amount of new data implies a narrow zone of credible parameter values. (p. 523)

## Multiplicative interaction of metric predictors

From page 526:

> Formally, interactions can have many different specific functional forms. We will consider multiplicative interaction. This means that the nonadditive interaction is expressed by multiplying the predictors. The predicted value is a weighted combination of the individual predictors and, additionally, the multiplicative product of the predictors. For two metric predictors, regression with multiplicative interaction has these algebraically equivalent expressions:

\begin{align*}
\mu & = \beta_0 + \beta_1 x_1 + \beta_2 x_2 + \beta_{1 \times 2} x_1 x_2 \\
    & = \beta_0 + \underbrace{(\beta_1 + \beta_{1 \times 2} x_2)}_{\text{slope of } x_1} x_1 + \beta_2 x_2 \\
    & = \beta_0 + \beta_1 x_1 + \underbrace{(\beta_2 + \beta_{1 \times 2} x_1)}_{\text{slope of } x_2} x_2.
\end{align*}

Figure 18.8 is out of our **ggplot2** repertoire. Even without it, we can still appreciate Kruschke's overall message that "Great care must be taken when interpreting the coefficients of a model that includes interaction terms [@braumoellerHypothesisTestingMultiplicative2004]. In particular, low-order terms are especially difficult to interpret when higher-order interactions are present" (p. 526). When in doubt, plot.

### An example.

Presuming we're still just modeling $\mu$ with two predictors, we can express the formula with the interaction term as

$$
\mu = \beta_0 + \beta_1+ \beta_2 x_2 + \underbrace{\beta_{1 \times 2}}_{\beta_3} \underbrace{x_2 x_1 }_{x_3}. 
$$

With **brms**, you can specify an interaction with either the `x_i*x_j` syntax or the `x_i:x_j` syntax. I typically use `x_i:x_j`. It's often the case that you can just make the interaction term right in the model formula. But since we're fitting the model with standardized predictors and then using Kruschke's equations to convert the parameters back to the unstandardized metric, it seems easier to make the interaction term in the data, first.


```r
my_data <-
  my_data %>% 
  # make x_3
  mutate(interaction   = Spend * PrcntTake) %>% 
  mutate(interaction_z = standardize(interaction))
```

Now we'll fit the model.


```r
fit18.3 <-
  brm(data = my_data,
      family = student,
      satt_z ~ 1 + spend_z + prcnt_take_z + interaction_z,
      prior = c(prior(normal(0, 2), class = Intercept),
                prior(normal(0, 2), class = b),
                prior(normal(0, 1), class = sigma),
                prior(exponential(one_over_twentynine), class = nu)),
      chains = 4, cores = 4,
      stanvars = stanvar(1/29, name = "one_over_twentynine"),
      seed = 18,
      file = "fits/fit18.03")
```

Note that even though an interaction term might seem different kind from other regression terms, it's just another coefficient of `class = b` as far as the `prior()` statements are concerned. Anyway, let's inspect the `summary()`.


```r
summary(fit18.3)
```

```
##  Family: student 
##   Links: mu = identity; sigma = identity; nu = identity 
## Formula: satt_z ~ 1 + spend_z + prcnt_take_z + interaction_z 
##    Data: my_data (Number of observations: 50) 
## Samples: 4 chains, each with iter = 2000; warmup = 1000; thin = 1;
##          total post-warmup samples = 4000
## 
## Population-Level Effects: 
##               Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
## Intercept        -0.00      0.06    -0.12     0.12 1.00     2807     2544
## spend_z           0.04      0.14    -0.25     0.33 1.00     1692     2031
## prcnt_take_z     -1.47      0.29    -2.06    -0.90 1.00     1613     2055
## interaction_z     0.58      0.37    -0.15     1.35 1.00     1516     1825
## 
## Family Specific Parameters: 
##       Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
## sigma     0.41      0.05     0.33     0.52 1.00     2395     2117
## nu       35.36     30.82     4.53   117.58 1.00     2328     2086
## 
## Samples were drawn using sampling(NUTS). For each parameter, Bulk_ESS
## and Tail_ESS are effective sample size measures, and Rhat is the potential
## scale reduction factor on split chains (at convergence, Rhat = 1).
```

The correlations among our parameters are about as severe as those in the text.


```r
vcov(fit18.3, correlation = T) %>% 
  round(digits = 3)
```

```
##               Intercept spend_z prcnt_take_z interaction_z
## Intercept         1.000   0.032        0.027        -0.033
## spend_z           0.032   1.000        0.731        -0.846
## prcnt_take_z      0.027   0.731        1.000        -0.965
## interaction_z    -0.033  -0.846       -0.965         1.000
```

> We can see that the interaction variable is strongly correlated with both predictors. Therefore, we know that there will be strong trade-offs among the regression coefficients, and the marginal distributions of single regression coefficients might be much wider than when there was no interaction included. (p. 528)

Let's convert the posterior draws to the unstandardized metric.


```r
sd_x_3 <- sd(my_data$interaction)
m_x_3  <- mean(my_data$interaction)

post <- 
  posterior_samples(fit18.3) %>% 
  transmute(Intercept = make_beta_0(zeta_0 = b_Intercept,
                                    zeta_1 = b_spend_z,
                                    zeta_2 = b_prcnt_take_z,
                                    zeta_3 = b_interaction_z,
                                    sd_x_1 = sd_x_1,
                                    sd_x_2 = sd_x_2,
                                    sd_x_3 = sd_x_3,
                                    sd_y   = sd_y,
                                    m_x_1  = m_x_1,
                                    m_x_2  = m_x_2,
                                    m_x_3  = m_x_3,
                                    m_y    = m_y),
            Spend = make_beta_j(zeta_j = b_spend_z,
                                sd_j   = sd_x_1,
                                sd_y   = sd_y),
            `Percent Take` = make_beta_j(zeta_j = b_prcnt_take_z,
                                         sd_j   = sd_x_2,
                                         sd_y   = sd_y),
            `Spend : Percent Take` = make_beta_j(zeta_j = b_interaction_z,
                                                 sd_j   = sd_x_3,
                                                 sd_y   = sd_y),
            Scale     = sigma * sd_y,
            Normality = nu %>% log10())

glimpse(post)
```

```
## Rows: 4,000
## Columns: 6
## $ Intercept              <dbl> 1041.6019, 1081.1576, 1066.1720, 1042.4374, 106…
## $ Spend                  <dbl> 7.2748793, -2.7466108, -1.9367335, 2.4689191, 0…
## $ `Percent Take`         <dbl> -4.410959, -3.911605, -3.734584, -3.723172, -3.…
## $ `Spend : Percent Take` <dbl> 0.192720404, 0.196408476, 0.209005153, 0.194968…
## $ Scale                  <dbl> 36.18685, 26.89591, 26.85517, 28.69350, 33.2069…
## $ Normality              <dbl> 2.2132809, 0.8124952, 0.7528365, 1.0375221, 1.1…
```

Now we've done the conversions, here are our versions of the histograms of Figure 18.9.


```r
post %>% 
  gather() %>% 
  
  ggplot(aes(x = value, y = 0)) +
  stat_wilke(normalize = "panels") +
  scale_y_continuous(NULL, breaks = NULL) +
  xlab(NULL) +
  coord_cartesian(ylim = c(-0.01, NA)) +
  panel_border() +
  theme(legend.position = "none") +
  facet_wrap(~ key, scales = "free", ncol = 3)
```

<img src="18_files/figure-html/unnamed-chunk-50-1.png" width="576" style="display: block; margin: auto;" />

"To properly understand the credible slopes on the two predictors, we must consider the credible slopes on each predictor as a function of the value of the other predictor" (p. 528). This is our motivation for the middle panel of Figure 18.9. To make it, we'll need to `expand()` our `post`, wrangle a bit, and plot with `geom_pointrange()`.


```r
# this will come in handy in `expand()`
bounds <- range(my_data$PrcntTake)

p1 <-
  # wrangle
  post %>% 
  expand(nesting(Spend, `Spend : Percent Take`),
         PrcntTake = seq(from = bounds[1], to = bounds[2], length.out = 20)) %>% 
  mutate(slope = Spend + `Spend : Percent Take` * PrcntTake) %>% 
  group_by(PrcntTake) %>% 
  median_hdi(slope) %>% 
  
  # plot
  ggplot(aes(x = PrcntTake, y = slope,
             ymin = .lower, ymax = .upper)) +
  geom_hline(yintercept = 0, color = "grey25", linetype = 2) +
  geom_pointrange(shape = 21, stroke = 1/10, fatten = 6, 
                  color = "steelblue4", fill = "chocolate3") +
  labs(title = expression("Slope on spend is "~beta[1]+beta[3]%.%prcnt_take),
       x = "Value of prcnt_take",
       y = "Slope on spend")
```

We'll follow the same basic order of operations for the final panel and then bind them together with **patchwork**.


```r
# this will come in handy in `expand()`
bounds <- range(my_data$Spend)

p2 <-
  # wrangle
  post %>% 
  expand(nesting(`Percent Take`, `Spend : Percent Take`),
         Spend = seq(from = bounds[1], to = bounds[2], length.out = 20)) %>% 
  mutate(slope = `Percent Take` + `Spend : Percent Take` * Spend) %>% 
  group_by(Spend) %>% 
  median_hdi(slope) %>% 
  
  # plot
  ggplot(aes(x = Spend, y = slope,
             ymin = .lower, ymax = .upper)) +
  geom_pointrange(shape = 21, stroke = 1/10, fatten = 6, 
                  color = "steelblue4", fill = "chocolate3") +
  labs(title = expression("Slope on prcnt_take is "~beta[2]+beta[3]%.%spend),
       x = "Value of spend",
       y = "Slope on prcnt_take")

p1 / p2
```

<img src="18_files/figure-html/unnamed-chunk-52-1.png" width="576" style="display: block; margin: auto;" />

Kruschke outlined all this in the opening paragraphs of page 530. His parting words of this subsection warrant repeating: "if you include an interaction term, you cannot ignore it even if its marginal posterior distribution includes zero" (p. 530).

## Shrinkage of regression coefficients

> In some research, there are many candidate predictors which we suspect could possibly be informative about the predicted variable. For example, when predicting college GPA, we might include high-school GPA, high-school SAT score, income of student, income of parents, years of education of the parents, spending per pupil at the student’s high school, student IQ, student height, weight, shoe size, hours of sleep per night, distance from home to school, amount of caffeine consumed, hours spent studying, hours spent earning a wage, blood pressure, etc. We can include all the candidate predictors in the model, with a regression coefficient for every predictor. And this is not even considering interactions, which we will ignore for now.
>
> With so many candidate predictors of noisy data, there may be some regression coefficients that are spuriously estimated to be non-zero. We would like some protection against accidentally nonzero regression coefficients. (p. 530)

That's what this section is all about. Figure 18.10 will give us a sense of what a model like this might look like.


```r
# brackets
p1 <-
  tibble(x = .5,
         y = .5,
         label = "{_}     {_}") %>% 
  
  ggplot(aes(x = x, y = y, label = label)) +
  geom_text(size = 10, family = "Times") +
  scale_x_continuous(expand = c(0, 0), limits = c(0, 1)) +
  ylim(0, 1) +
  theme_void()

#  two annotated arrows
p2 <-
  tibble(x    = c(.15, .85),
         y    = c(1, 1),
         xend = c(.25, .75),
         yend = c(.2, .2)) %>%
  
  ggplot(aes(x = x, xend = xend,
             y = y, yend = yend)) +
  geom_segment(arrow = my_arrow) +
  xlim(0, 1) +
  theme_void()

# normal density
p3 <-
  tibble(x = seq(from = -3, to = 3, by = .1)) %>% 
  ggplot(aes(x = x, y = (dnorm(x)) / max(dnorm(x)))) +
  geom_area(fill = "steelblue4", color = "steelblue4", alpha = .6) +
  annotate(geom = "text",
           x = 0, y = .2,
           label = "normal",
           size = 7) +
  annotate(geom = "text",
           x = c(0, 1.5), y = .6,
           label = c("italic(M)[0]", "italic(S)[0]"), 
           size = 7, family = "Times", parse = T) +
  scale_x_continuous(expand = c(0, 0)) +
  theme_void() +
  theme(axis.line.x = element_line(size = 0.5))

# a student-t density
p4 <-
  tibble(x = seq(from = -3, to = 3, by = .1)) %>% 
  ggplot(aes(x = x, y = (dt(x, 3) / max(dt(x, 3))))) +
  geom_area(fill = "steelblue4", color = "steelblue4", alpha = .6) +
  annotate(geom = "text",
           x = 0, y = .2,
           label = "student t",
           size = 7) +
  annotate(geom = "text",
           x = 0, y = .6,
           label = "nu[beta]~~~0~~~sigma[beta]",
           size = 7, family = "Times", parse = T) +
  scale_x_continuous(expand = c(0, 0)) +
  theme_void() +
  theme(axis.line.x = element_line(size = 0.5))

# two more annotated arrows
p5 <-
  tibble(x    = c(.33, 1.67),
         y    = c(1, 1),
         xend = c(.63, 1.2),
         yend = c(0, 0)) %>%
  
  ggplot(aes(x = x, xend = xend,
             y = y, yend = yend)) +
  geom_segment(arrow = my_arrow) +
  annotate(geom = "text",
           x = c(.35, 1.35, 1.54), y = .5,
           label = c("'~'", "'~'", "italic(j)"),
           size = c(10, 10, 7), family = "Times", parse = T) +
  xlim(0, 2) +
  theme_void()

# exponential density
p6 <-
  tibble(x = seq(from = 0, to = 1, by = .01)) %>% 
  ggplot(aes(x = x, y = (dexp(x, 2) / max(dexp(x, 2))))) +
  geom_area(fill = "steelblue4", color = "steelblue4", alpha = .6) +
  annotate(geom = "text",
           x = .5, y = .2,
           label = "exp",
           size = 7) +
  annotate(geom = "text",
           x = .5, y = .6,
           label = "italic(K)",
           size = 7, family = "Times", parse = T) +
  scale_x_continuous(expand = c(0, 0)) +
  theme_void() +
  theme(axis.line.x = element_line(size = 0.5))

# likelihood formula
p7 <-
  tibble(x = .5,
         y = .25,
         label = "beta[0]+sum()[italic(j)]*beta[italic(j)]*italic(x)[italic(ji)]") %>% 
  
  ggplot(aes(x = x, y = y, label = label)) +
  geom_text(size = 7, parse = T, family = "Times") +
  scale_x_continuous(expand = c(0, 0), limits = c(0, 1)) +
  ylim(0, 1) +
  theme_void()
  
  # half-normal density
p8 <-
  tibble(x = seq(from = 0, to = 3, by = .01)) %>% 
  ggplot(aes(x = x, y = (dnorm(x)) / max(dnorm(x)))) +
  geom_area(fill = "steelblue4", color = "steelblue4", alpha = .6) +
  annotate(geom = "text",
           x = 1.5, y = .2,
           label = "half-normal",
           size = 7) +
  annotate(geom = "text",
           x = 1.5, y = .6,
           label = "0*','*~italic(S)[sigma]", 
           size = 7, family = "Times", parse = T) +
  scale_x_continuous(expand = c(0, 0)) +
  theme_void() +
  theme(axis.line.x = element_line(size = 0.5))

# four annotated arrows
p9 <-
  tibble(x    = c(.43, .43, 1.5, 2.5),
         y    = c(1, .55, 1, 1),
         xend = c(.43, 1.225, 1.5, 1.75),
         yend = c(.8, .15, .2, .2)) %>%
  
  ggplot(aes(x = x, xend = xend,
             y = y, yend = yend)) +
  geom_segment(arrow = my_arrow) +
  annotate(geom = "text",
           x = c(.3, .7, 1.38, 2), y = c(.92, .22, .65, .6),
           label = c("'~'", "'='", "'='", "'~'"),
           size = 10, family = "Times", parse = T) +
  annotate(geom = "text",
           x = .43, y = .7,
           label = "nu*minute+1",
           size = 7, family = "Times", parse = T) +
  xlim(0, 3) +
  theme_void()

# a second student-t density
p10 <-
  tibble(x = seq(from = -3, to = 3, by = .1)) %>% 
  ggplot(aes(x = x, y = (dt(x, 3) / max(dt(x, 3))))) +
  geom_area(fill = "steelblue4", color = "steelblue4", alpha = .6) +
  annotate(geom = "text",
           x = 0, y = .2,
           label = "student t",
           size = 7) +
  annotate(geom = "text",
           x = 0, y = .6,
           label = "nu~~~mu[italic(i)]~~~sigma",
           size = 7, family = "Times", parse = T) +
  scale_x_continuous(expand = c(0, 0)) +
  theme_void() +
  theme(axis.line.x = element_line(size = 0.5))

# the final annotated arrow
p11 <-
  tibble(x     = c(.375, .625),
         y     = c(1/3, 1/3),
         label = c("'~'", "italic(i)")) %>% 
  
  ggplot(aes(x = x, y = y, label = label)) +
  geom_text(size = c(10, 7), parse = T, family = "Times") +
  geom_segment(x = .5, xend = .5,
               y = 1, yend = 0, 
               arrow = my_arrow) +
  xlim(0, 1) +
  theme_void()

# some text
p12 <-
  tibble(x     = .5,
         y     = .5,
         label = "italic(y[i])") %>% 
  
  ggplot(aes(x = x, y = y, label = label)) +
  geom_text(size = 7, parse = T, family = "Times") +
  xlim(0, 1) +
  theme_void()

# define the layout
layout <- c(
  area(t = 1, b = 1, l = 7, r = 9),
  area(t = 3, b = 4, l = 3, r = 5),
  area(t = 3, b = 4, l = 7, r = 9),
  area(t = 2, b = 3, l = 7, r = 9),
  area(t = 6, b = 7, l = 1, r = 3),
  area(t = 6, b = 7, l = 5, r = 7),
  area(t = 6, b = 7, l = 9, r = 11),
  area(t = 5, b = 6, l = 3, r = 9),
  area(t = 9, b = 10, l = 5, r = 7),
  area(t = 8, b = 9, l = 1, r = 11),
  area(t = 11, b = 11, l = 5, r = 7),
  area(t = 12, b = 12, l = 5, r = 7)
)

# combine and plot!
(p1 + p3 + p4 + p2 + p6 + p7 + p8 + p5 + p10 + p9 + p11 + p12) + 
  plot_layout(design = layout) &
  ylim(0, 1) &
  theme(plot.margin = margin(0, 5.5, 0, 5.5))
```

<img src="18_files/figure-html/unnamed-chunk-53-1.png" width="624" style="display: block; margin: auto;" />

Make our random noise predictors with `rnorm()`.


```r
set.seed(18)
my_data <-
  my_data %>% 
  mutate(x_rand_1  = rnorm(n = n(), mean = 0, sd = 1),
         x_rand_2  = rnorm(n = n(), mean = 0, sd = 1),
         x_rand_3  = rnorm(n = n(), mean = 0, sd = 1),
         x_rand_4  = rnorm(n = n(), mean = 0, sd = 1),
         x_rand_5  = rnorm(n = n(), mean = 0, sd = 1),
         x_rand_6  = rnorm(n = n(), mean = 0, sd = 1),
         x_rand_7  = rnorm(n = n(), mean = 0, sd = 1),
         x_rand_8  = rnorm(n = n(), mean = 0, sd = 1),
         x_rand_9  = rnorm(n = n(), mean = 0, sd = 1),
         x_rand_10 = rnorm(n = n(), mean = 0, sd = 1),
         x_rand_11 = rnorm(n = n(), mean = 0, sd = 1),
         x_rand_12 = rnorm(n = n(), mean = 0, sd = 1))

glimpse(my_data)
```

```
## Rows: 50
## Columns: 27
## $ State           <chr> "Alabama", "Alaska", "Arizona", "Arkansas", "Californi…
## $ Spend           <dbl> 4.405, 8.963, 4.778, 4.459, 4.992, 5.443, 8.817, 7.030…
## $ StuTeaRat       <dbl> 17.2, 17.6, 19.3, 17.1, 24.0, 18.4, 14.4, 16.6, 19.1, …
## $ Salary          <dbl> 31.144, 47.951, 32.175, 28.934, 41.078, 34.571, 50.045…
## $ PrcntTake       <dbl> 8, 47, 27, 6, 45, 29, 81, 68, 48, 65, 57, 15, 13, 58, …
## $ SATV            <dbl> 491, 445, 448, 482, 417, 462, 431, 429, 420, 406, 407,…
## $ SATM            <dbl> 538, 489, 496, 523, 485, 518, 477, 468, 469, 448, 482,…
## $ SATT            <dbl> 1029, 934, 944, 1005, 902, 980, 908, 897, 889, 854, 88…
## $ prcnt_take_z    <dbl> -1.0178453, 0.4394222, -0.3078945, -1.0925770, 0.36469…
## $ spend_z         <dbl> -1.10086058, 2.24370805, -0.82716069, -1.06123647, -0.…
## $ satt_z          <dbl> 0.8430838, -0.4266207, -0.2929676, 0.5223163, -0.85431…
## $ prop_not_take   <dbl> 0.92, 0.53, 0.73, 0.94, 0.55, 0.71, 0.19, 0.32, 0.52, …
## $ prop_not_take_z <dbl> 1.0178453, -0.4394222, 0.3078945, 1.0925770, -0.364690…
## $ interaction     <dbl> 35.240, 421.261, 129.006, 26.754, 224.640, 157.847, 71…
## $ interaction_z   <dbl> -0.94113720, 0.93111798, -0.48635915, -0.98229547, -0.…
## $ x_rand_1        <dbl> 0.92645924, 1.82282117, -1.61056690, -0.28510975, -0.3…
## $ x_rand_2        <dbl> -0.90258025, -1.13163679, 0.49708131, -0.54771876, -0.…
## $ x_rand_3        <dbl> 0.51576102, 0.30710965, 0.66199996, 2.21990655, -2.041…
## $ x_rand_4        <dbl> 1.08730491, -1.23909473, 0.43161390, 1.06733141, -0.78…
## $ x_rand_5        <dbl> -0.23846777, 0.15702031, -1.02132795, 0.75395217, -2.3…
## $ x_rand_6        <dbl> 0.06014956, 1.00555800, 1.47981871, -0.82827890, -0.58…
## $ x_rand_7        <dbl> 1.46961709, 0.51790320, -2.33110353, 0.11339996, 1.726…
## $ x_rand_8        <dbl> 0.03463437, -1.48737599, -0.01528284, 0.48480309, 0.20…
## $ x_rand_9        <dbl> -0.4556078, -0.7035475, -0.5001913, -0.6526022, 0.7742…
## $ x_rand_10       <dbl> 1.2858586, -0.7474640, -0.3107255, -1.1037468, 0.33136…
## $ x_rand_11       <dbl> 0.17236599, -0.37956084, 0.31982301, 0.29678108, 1.220…
## $ x_rand_12       <dbl> -0.53048519, 0.92465424, 0.66876661, 0.30935146, 1.474…
```

Here's the naïve model.


```r
fit18.4 <-
  update(fit18.1, 
         newdata = my_data,
         formula = satt_z ~ 1 + prcnt_take_z + spend_z + x_rand_1 + x_rand_2 + x_rand_3 + x_rand_4 + x_rand_5 + x_rand_6 + x_rand_7 + x_rand_8 + x_rand_9 + x_rand_10 + x_rand_11 + x_rand_12,
         seed = 18,
         file = "fits/fit18.04")
```

Here we'll examine the posterior with `posterior_summary()`.


```r
posterior_summary(fit18.4) %>% 
  round(digits = 2)
```

```
##                Estimate Est.Error   Q2.5  Q97.5
## b_Intercept       -0.02      0.07  -0.16   0.11
## b_prcnt_take_z    -1.11      0.09  -1.29  -0.94
## b_spend_z          0.32      0.09   0.15   0.49
## b_x_rand_1         0.03      0.06  -0.09   0.15
## b_x_rand_2         0.02      0.09  -0.15   0.21
## b_x_rand_3         0.09      0.07  -0.05   0.23
## b_x_rand_4        -0.09      0.07  -0.23   0.05
## b_x_rand_5         0.00      0.06  -0.12   0.13
## b_x_rand_6        -0.02      0.08  -0.17   0.13
## b_x_rand_7        -0.02      0.07  -0.17   0.12
## b_x_rand_8        -0.18      0.07  -0.31  -0.04
## b_x_rand_9         0.13      0.06   0.01   0.25
## b_x_rand_10        0.00      0.05  -0.11   0.10
## b_x_rand_11        0.05      0.09  -0.13   0.23
## b_x_rand_12       -0.08      0.06  -0.21   0.04
## sigma              0.39      0.07   0.24   0.52
## nu                25.85     26.51   2.17  96.68
## lp__             -54.94      3.55 -62.91 -49.30
```

Before we can make Figure 18.11, we'll need to update our `make_beta_0()` function to accommodate this model.


```r
make_beta_0 <- 
  function(zeta_0, zeta_1, zeta_2, zeta_3, zeta_4, zeta_5, zeta_6, zeta_7, zeta_8, zeta_9, zeta_10, zeta_11, zeta_12, zeta_13, zeta_14, 
           sd_x_1, sd_x_2, sd_x_3, sd_x_4, sd_x_5, sd_x_6, sd_x_7, sd_x_8, sd_x_9, sd_x_10, sd_x_11, sd_x_12, sd_x_13, sd_x_14, sd_y, 
           m_x_1, m_x_2, m_x_3, m_x_4, m_x_5, m_x_6, m_x_7, m_x_8, m_x_9, m_x_10, m_x_11, m_x_12, m_x_13, m_x_14, m_y) {
    sd_y * zeta_0 + m_y - sd_y * ((zeta_1 * m_x_1 / sd_x_1) + 
                                    (zeta_2 * m_x_2 / sd_x_2) + 
                                    (zeta_3 * m_x_3 / sd_x_3) + 
                                    (zeta_4 * m_x_4 / sd_x_4) + 
                                    (zeta_5 * m_x_5 / sd_x_5) + 
                                    (zeta_6 * m_x_6 / sd_x_6) + 
                                    (zeta_7 * m_x_7 / sd_x_7) + 
                                    (zeta_8 * m_x_8 / sd_x_8) + 
                                    (zeta_9 * m_x_9 / sd_x_9) + 
                                    (zeta_10 * m_x_10 / sd_x_10) + 
                                    (zeta_11 * m_x_11 / sd_x_11) + 
                                    (zeta_12 * m_x_12 / sd_x_12) + 
                                    (zeta_13 * m_x_13 / sd_x_13) + 
                                    (zeta_14 * m_x_14 / sd_x_14))
}
```

*Sigh*, our poor `make_beta_0()` and `make_beta_1()` code is getting obscene. I don't have the energy to think of how to wrap this into a simpler function. Someone probably should. If that ends up as you, [do share your code](https://github.com/ASKurz/Doing-Bayesian-Data-Analysis-in-brms-and-the-tidyverse/issues).


```r
sd_x_1  <- sd(my_data$Spend)
sd_x_2  <- sd(my_data$PrcntTake)
sd_x_3  <- sd(my_data$x_rand_1)
sd_x_4  <- sd(my_data$x_rand_2)
sd_x_5  <- sd(my_data$x_rand_3)
sd_x_6  <- sd(my_data$x_rand_4)
sd_x_7  <- sd(my_data$x_rand_5)
sd_x_8  <- sd(my_data$x_rand_6)
sd_x_9  <- sd(my_data$x_rand_7)
sd_x_10 <- sd(my_data$x_rand_8)
sd_x_11 <- sd(my_data$x_rand_9)
sd_x_12 <- sd(my_data$x_rand_10)
sd_x_13 <- sd(my_data$x_rand_11)
sd_x_14 <- sd(my_data$x_rand_12)
sd_y    <- sd(my_data$SATT)

m_x_1  <- mean(my_data$Spend)
m_x_2  <- mean(my_data$PrcntTake)
m_x_3  <- mean(my_data$x_rand_1)
m_x_4  <- mean(my_data$x_rand_2)
m_x_5  <- mean(my_data$x_rand_3)
m_x_6  <- mean(my_data$x_rand_4)
m_x_7  <- mean(my_data$x_rand_5)
m_x_8  <- mean(my_data$x_rand_6)
m_x_9  <- mean(my_data$x_rand_7)
m_x_10 <- mean(my_data$x_rand_8)
m_x_11 <- mean(my_data$x_rand_9)
m_x_12 <- mean(my_data$x_rand_10)
m_x_13 <- mean(my_data$x_rand_11)
m_x_14 <- mean(my_data$x_rand_12)
m_y    <- mean(my_data$SATT)

post <-
  posterior_samples(fit18.4) %>% 
  transmute(Intercept      = make_beta_0(zeta_0 = b_Intercept,
                                         zeta_1  = b_spend_z,
                                         zeta_2  = b_prcnt_take_z,
                                         zeta_3  = b_x_rand_1,
                                         zeta_4  = b_x_rand_2,
                                         zeta_5  = b_x_rand_3,
                                         zeta_6  = b_x_rand_4,
                                         zeta_7  = b_x_rand_5,
                                         zeta_8  = b_x_rand_6,
                                         zeta_9  = b_x_rand_7,
                                         zeta_10 = b_x_rand_8,
                                         zeta_11 = b_x_rand_9,
                                         zeta_12 = b_x_rand_10,
                                         zeta_13 = b_x_rand_11,
                                         zeta_14 = b_x_rand_12,
                                         sd_x_1  = sd_x_1,
                                         sd_x_2  = sd_x_2,
                                         sd_x_3  = sd_x_3,
                                         sd_x_4  = sd_x_4,
                                         sd_x_5  = sd_x_5,
                                         sd_x_6  = sd_x_6,
                                         sd_x_7  = sd_x_7,
                                         sd_x_8  = sd_x_8,
                                         sd_x_9  = sd_x_9,
                                         sd_x_10 = sd_x_10,
                                         sd_x_11 = sd_x_11,
                                         sd_x_12 = sd_x_12,
                                         sd_x_13 = sd_x_13,
                                         sd_x_14 = sd_x_14,
                                         sd_y    = sd_y,
                                         m_x_1   = m_x_1,
                                         m_x_2   = m_x_2,
                                         m_x_3   = m_x_3,
                                         m_x_4   = m_x_4,
                                         m_x_5   = m_x_5,
                                         m_x_6   = m_x_6,
                                         m_x_7   = m_x_7,
                                         m_x_8   = m_x_8,
                                         m_x_9   = m_x_9,
                                         m_x_10  = m_x_10,
                                         m_x_11  = m_x_11,
                                         m_x_12  = m_x_12,
                                         m_x_13  = m_x_13,
                                         m_x_14  = m_x_14,
                                         m_y     = m_y),
            Spend          = make_beta_j(zeta_j = b_spend_z,
                                         sd_j   = sd_x_1,
                                         sd_y   = sd_y),
            `Percent Take` = make_beta_j(zeta_j = b_prcnt_take_z,
                                         sd_j   = sd_x_2,
                                         sd_y   = sd_y),
            x_rand_1       = make_beta_j(zeta_j = b_x_rand_1,
                                         sd_j   = sd_x_3,
                                         sd_y   = sd_y),
            x_rand_2       = make_beta_j(zeta_j = b_x_rand_2,
                                         sd_j   = sd_x_4,
                                         sd_y   = sd_y),
            x_rand_3       = make_beta_j(zeta_j = b_x_rand_3,
                                         sd_j   = sd_x_5,
                                         sd_y   = sd_y),
            x_rand_4       = make_beta_j(zeta_j = b_x_rand_4,
                                         sd_j   = sd_x_6,
                                         sd_y   = sd_y),
            x_rand_5       = make_beta_j(zeta_j = b_x_rand_5,
                                         sd_j   = sd_x_7,
                                         sd_y   = sd_y),
            x_rand_6       = make_beta_j(zeta_j = b_x_rand_6,
                                         sd_j   = sd_x_8,
                                         sd_y   = sd_y),
            x_rand_7       = make_beta_j(zeta_j = b_x_rand_7,
                                         sd_j   = sd_x_9,
                                         sd_y   = sd_y),
            x_rand_8       = make_beta_j(zeta_j = b_x_rand_8,
                                         sd_j   = sd_x_10,
                                         sd_y   = sd_y),
            x_rand_9       = make_beta_j(zeta_j = b_x_rand_9,
                                         sd_j   = sd_x_11,
                                         sd_y   = sd_y),
            x_rand_10      = make_beta_j(zeta_j = b_x_rand_10,
                                         sd_j   = sd_x_12,
                                         sd_y   = sd_y),
            x_rand_11      = make_beta_j(zeta_j = b_x_rand_11,
                                         sd_j   = sd_x_13,
                                         sd_y   = sd_y),
            x_rand_12      = make_beta_j(zeta_j = b_x_rand_12,
                                         sd_j   = sd_x_14,
                                         sd_y   = sd_y),
            Scale          = sigma * sd_y,
            Normality      = nu %>% log10())

glimpse(post)
```

```
## Rows: 4,000
## Columns: 17
## $ Intercept      <dbl> 964.3338, 1012.8831, 937.1941, 956.2408, 953.6869, 942.…
## $ Spend          <dbl> 17.70176, 10.52307, 23.34652, 21.40584, 16.23480, 23.16…
## $ `Percent Take` <dbl> -3.107366, -3.031856, -3.323062, -3.249976, -2.847786, …
## $ x_rand_1       <dbl> -6.6119446, 8.4194659, -1.4197652, 7.0232430, 9.5633689…
## $ x_rand_2       <dbl> -1.6112923, 13.7991007, -11.7892439, 22.4568434, -5.895…
## $ x_rand_3       <dbl> 6.148340, 8.578023, 3.085607, 6.254136, 5.504113, 7.819…
## $ x_rand_4       <dbl> -6.3966120, -1.9820812, -7.7143985, -12.7959392, 1.4773…
## $ x_rand_5       <dbl> -1.428088102, 3.457773345, -0.007853016, 5.774369871, -…
## $ x_rand_6       <dbl> 6.5590291, -9.7621430, 9.3611323, -2.8690390, 5.3356383…
## $ x_rand_7       <dbl> 6.9282426, -5.6127407, 0.2350071, 4.1839229, -1.1852527…
## $ x_rand_8       <dbl> -16.873853, -8.831986, -15.164424, -16.118147, -19.1949…
## $ x_rand_9       <dbl> 5.287702, 9.133591, 6.841819, 9.123481, 8.006589, 12.42…
## $ x_rand_10      <dbl> 0.9329838, 1.7490086, -1.7428759, -2.9719657, 2.1464901…
## $ x_rand_11      <dbl> -1.570062, 5.739023, 1.528312, 9.747208, 12.516541, 19.…
## $ x_rand_12      <dbl> 1.3676726, -11.6097384, -0.1440136, -7.8859090, -1.5697…
## $ Scale          <dbl> 31.01471, 24.72028, 26.50818, 31.64840, 31.11237, 32.36…
## $ Normality      <dbl> 2.2698309, 0.8892687, 1.0866731, 1.2285727, 1.0237282, …
```

Okay, here are our versions of the histograms of Figure 18.11.


```r
post %>% 
  select(Intercept:x_rand_3, x_rand_10:Normality) %>% 
  gather() %>% 
  mutate(key = factor(key, 
                      levels = c("Intercept", "Spend", "Percent Take",
                                 "x_rand_1", "x_rand_2", "x_rand_3",
                                 "x_rand_10", "x_rand_11", "x_rand_12",
                                 "Scale", "Normality"))) %>% 
  
  ggplot(aes(x = value, y = 0)) +
  stat_wilke(normalize = "panels") +
  scale_y_continuous(NULL, breaks = NULL) +
  xlab(NULL) +
  coord_cartesian(ylim = c(-0.01, NA)) +
  panel_border() +
  theme(axis.text.x = element_text(size = 9),
        legend.position = c(.74, .09)) +
  facet_wrap(~ key, scales = "free", ncol = 3)
```

<img src="18_files/figure-html/unnamed-chunk-58-1.png" width="576" style="display: block; margin: auto;" />

And here's the final density plot depicting the Bayesian $R^2$.


```r
bayes_R2(fit18.4, summary = F) %>% 
  as_tibble() %>% 
  
  ggplot(aes(x = R2, y = 0)) +
  stat_wilke() +
  scale_y_continuous(NULL, breaks = NULL) +
  labs(subtitle = expression(paste("Bayesian ", italic(R)^2)),
       x = NULL) +
  coord_cartesian(xlim = c(0, 1),
                  ylim = c(-0.01, NA)) +
  theme(legend.position = c(.01, .8))
```

<img src="18_files/figure-html/unnamed-chunk-59-1.png" width="336" style="display: block; margin: auto;" />

Note that unlike the one Kruschke displayed in the text, our `brms::bayes_R2()`-based $R^2$ distribution did not exceed the logical right bound of 1.

Sometimes when you have this many parameters you'd like to compare, it's better to display their summaries with an ordered coefficient plot.


```r
post %>% 
  select(Spend:x_rand_12) %>% 
  gather() %>% 
  mutate(key = fct_reorder(key, value)) %>% 
  
  ggplot(aes(x = value, y = key)) +
  geom_vline(xintercept = 0, color = "grey25", linetype = 2) +
  stat_pointinterval(point_interval = mode_hdi, .width = .95, point_size = 4,
                     color = "steelblue4", point_color = "chocolate3") +
  labs(x = NULL,
       y = NULL) +
  theme(axis.text.y = element_text(hjust = 0))
```

<img src="18_files/figure-html/unnamed-chunk-60-1.png" width="768" style="display: block; margin: auto;" />

Now we can see that by chance alone, the coefficients for `x_rand_8` and `x_rand_9` are clearly distinct from zero. Our `stat_wilke()` function can be informative, too.


```r
post %>% 
  select(Spend:x_rand_12) %>% 
  gather() %>% 
  
  ggplot(aes(x = value, y = reorder(key, value), group = reorder(key, value))) +
  geom_vline(xintercept = 0, color = "grey25", linetype = 2) +
  stat_wilke(height = 10, point_size = 3) +
  labs(x = NULL,
       y = NULL) +
  coord_cartesian(ylim = c(1.25, 14.5)) +
  theme(axis.text.y = element_text(hjust = 0),
        legend.position = c(.785, .13)) 
```

<img src="18_files/figure-html/unnamed-chunk-61-1.png" width="768" style="display: block; margin: auto;" />

With **brms**, we can fit something like the model Kruschke displayed in Figure 18.12 with the `horseshoe()` prior. From the `horseshoe` section of the [**brms** reference manual](https://CRAN.R-project.org/package=brms/brms.pdf):

> The horseshoe prior is a special shrinkage prior initially proposed by [@carvalho2009handling]. It is symmetric around zero with fat tails and an infinitely large spike at zero. This makes it ideal for sparse models that have many regression coefficients, although only a minority of them is non-zero. The horseshoe prior can be applied on all population-level effects at once (excluding the intercept) by using `set_prior("horseshoe(1)")`. The `1` implies that the student-t prior of the local shrinkage parameters has 1 degrees of freedom [@brms2021RM, p. 97]

Based on the quote, here's how to fit our horseshoe-prior model.


```r
fit18.5 <-
  update(fit18.4, 
         newdata = my_data,
         formula = satt_z ~ 1 + prcnt_take_z + spend_z + x_rand_1 + x_rand_2 + x_rand_3 + x_rand_4 + x_rand_5 + x_rand_6 + x_rand_7 + x_rand_8 + x_rand_9 + x_rand_10 + x_rand_11 + x_rand_12,
         prior = c(prior(normal(0, 2), class = Intercept),
                   prior(horseshoe(1), class = b),
                   prior(normal(0, 1), class = sigma),
                   prior(exponential(one_over_twentynine), class = nu)),
         seed = 18,
      file = "fits/fit18.05")
```

Check the parameter summary.


```r
posterior_summary(fit18.5) %>% 
  round(digits = 2)
```

```
##                Estimate Est.Error   Q2.5  Q97.5
## b_Intercept       -0.02      0.07  -0.14   0.12
## b_prcnt_take_z    -1.02      0.10  -1.20  -0.83
## b_spend_z          0.20      0.11   0.00   0.39
## b_x_rand_1         0.01      0.04  -0.05   0.11
## b_x_rand_2         0.01      0.04  -0.08   0.11
## b_x_rand_3         0.02      0.04  -0.06   0.12
## b_x_rand_4        -0.03      0.05  -0.14   0.05
## b_x_rand_5         0.00      0.03  -0.07   0.08
## b_x_rand_6        -0.02      0.04  -0.13   0.06
## b_x_rand_7        -0.01      0.04  -0.09   0.07
## b_x_rand_8        -0.09      0.07  -0.24   0.01
## b_x_rand_9         0.05      0.05  -0.02   0.17
## b_x_rand_10        0.00      0.03  -0.06   0.07
## b_x_rand_11        0.01      0.04  -0.07   0.12
## b_x_rand_12       -0.02      0.04  -0.12   0.04
## sigma              0.40      0.06   0.27   0.51
## nu                30.37     27.47   2.88 104.34
## lp__             -81.90      5.82 -94.43 -71.67
```

Our `make_beta_0()` and `make_beta_1()` code remains obscene.


```r
post <-
  posterior_samples(fit18.5) %>% 
  transmute(Intercept      = make_beta_0(zeta_0  = b_Intercept,
                                         zeta_1  = b_spend_z,
                                         zeta_2  = b_prcnt_take_z,
                                         zeta_3  = b_x_rand_1,
                                         zeta_4  = b_x_rand_2,
                                         zeta_5  = b_x_rand_3,
                                         zeta_6  = b_x_rand_4,
                                         zeta_7  = b_x_rand_5,
                                         zeta_8  = b_x_rand_6,
                                         zeta_9  = b_x_rand_7,
                                         zeta_10 = b_x_rand_8,
                                         zeta_11 = b_x_rand_9,
                                         zeta_12 = b_x_rand_10,
                                         zeta_13 = b_x_rand_11,
                                         zeta_14 = b_x_rand_12,
                                         sd_x_1  = sd_x_1,
                                         sd_x_2  = sd_x_2,
                                         sd_x_3  = sd_x_3,
                                         sd_x_4  = sd_x_4,
                                         sd_x_5  = sd_x_5,
                                         sd_x_6  = sd_x_6,
                                         sd_x_7  = sd_x_7,
                                         sd_x_8  = sd_x_8,
                                         sd_x_9  = sd_x_9,
                                         sd_x_10 = sd_x_10,
                                         sd_x_11 = sd_x_11,
                                         sd_x_12 = sd_x_12,
                                         sd_x_13 = sd_x_13,
                                         sd_x_14 = sd_x_14,
                                         sd_y    = sd_y,
                                         m_x_1   = m_x_1,
                                         m_x_2   = m_x_2,
                                         m_x_3   = m_x_3,
                                         m_x_4   = m_x_4,
                                         m_x_5   = m_x_5,
                                         m_x_6   = m_x_6,
                                         m_x_7   = m_x_7,
                                         m_x_8   = m_x_8,
                                         m_x_9   = m_x_9,
                                         m_x_10  = m_x_10,
                                         m_x_11  = m_x_11,
                                         m_x_12  = m_x_12,
                                         m_x_13  = m_x_13,
                                         m_x_14  = m_x_14,
                                         m_y     = m_y),
            Spend          = make_beta_j(zeta_j = b_spend_z,
                                         sd_j   = sd_x_1,
                                         sd_y   = sd_y),
            `Percent Take` = make_beta_j(zeta_j = b_prcnt_take_z,
                                         sd_j   = sd_x_2,
                                         sd_y   = sd_y),
            x_rand_1       = make_beta_j(zeta_j = b_x_rand_1,
                                         sd_j   = sd_x_3,
                                         sd_y   = sd_y),
            x_rand_2       = make_beta_j(zeta_j = b_x_rand_2,
                                         sd_j   = sd_x_4,
                                         sd_y   = sd_y),
            x_rand_3       = make_beta_j(zeta_j = b_x_rand_3,
                                         sd_j   = sd_x_5,
                                         sd_y   = sd_y),
            x_rand_4       = make_beta_j(zeta_j = b_x_rand_4,
                                         sd_j   = sd_x_6,
                                         sd_y   = sd_y),
            x_rand_5       = make_beta_j(zeta_j = b_x_rand_5,
                                         sd_j   = sd_x_7,
                                         sd_y   = sd_y),
            x_rand_6       = make_beta_j(zeta_j = b_x_rand_6,
                                         sd_j   = sd_x_8,
                                         sd_y   = sd_y),
            x_rand_7       = make_beta_j(zeta_j = b_x_rand_7,
                                         sd_j   = sd_x_9,
                                         sd_y   = sd_y),
            x_rand_8       = make_beta_j(zeta_j = b_x_rand_8,
                                         sd_j   = sd_x_10,
                                         sd_y   = sd_y),
            x_rand_9       = make_beta_j(zeta_j = b_x_rand_9,
                                         sd_j   = sd_x_11,
                                         sd_y   = sd_y),
            x_rand_10      = make_beta_j(zeta_j = b_x_rand_10,
                                         sd_j   = sd_x_12,
                                         sd_y   = sd_y),
            x_rand_11      = make_beta_j(zeta_j = b_x_rand_11,
                                         sd_j   = sd_x_13,
                                         sd_y   = sd_y),
            x_rand_12      = make_beta_j(zeta_j = b_x_rand_12,
                                         sd_j   = sd_x_14,
                                         sd_y   = sd_y),
            Scale          = sigma * sd_y,
            Normality      = nu %>% log10())

glimpse(post)
```

```
## Rows: 4,000
## Columns: 17
## $ Intercept      <dbl> 981.4779, 970.1863, 988.7498, 964.3090, 1004.5032, 995.…
## $ Spend          <dbl> 12.9379305, 17.4669290, 14.4433499, 16.5670739, 9.75457…
## $ `Percent Take` <dbl> -2.645357, -3.268805, -3.183415, -2.894095, -2.746933, …
## $ x_rand_1       <dbl> 0.366191006, 0.519764973, 9.095903317, 1.111286218, -2.…
## $ x_rand_2       <dbl> 1.95189226, 0.28299854, -6.76883100, 4.22917780, -6.699…
## $ x_rand_3       <dbl> -0.2429880, 0.2501174, 2.1171855, -3.4842102, 1.6859508…
## $ x_rand_4       <dbl> -2.98786555, -12.95661261, 3.69505161, -0.27868075, 0.1…
## $ x_rand_5       <dbl> -0.63984463, -0.62881551, -0.16943596, 0.02814921, 1.25…
## $ x_rand_6       <dbl> -3.5577374, -2.2434265, -0.5332872, -1.0015634, -8.1125…
## $ x_rand_7       <dbl> 0.79938479, 0.14699754, -0.48606985, 1.24884146, 0.2260…
## $ x_rand_8       <dbl> -1.3973020, -12.7224426, -1.5969579, -18.1994295, -1.48…
## $ x_rand_9       <dbl> -0.004590364, -0.078675192, 2.658891612, 9.206196152, 0…
## $ x_rand_10      <dbl> 0.003225641, 0.394649949, -0.537956392, -0.004349622, -…
## $ x_rand_11      <dbl> -3.00848415, -0.61936646, 8.49428180, -6.66462328, 2.62…
## $ x_rand_12      <dbl> -3.10166126, -3.49699104, -4.39092856, 0.93563459, 0.18…
## $ Scale          <dbl> 31.05865, 28.87254, 24.99298, 29.30649, 32.27190, 28.69…
## $ Normality      <dbl> 1.5388681, 1.2011831, 0.8226206, 1.3163185, 1.5625397, …
```

And here are our `stat_wilke()` plot versions of the majority of the histograms of Figure 18.12.


```r
post %>% 
  select(Intercept:x_rand_3, x_rand_10:Normality) %>% 
  gather() %>% 
  mutate(key = factor(key, 
                      levels = c("Intercept", "Spend", "Percent Take",
                                 "x_rand_1", "x_rand_2", "x_rand_3",
                                 "x_rand_10", "x_rand_11", "x_rand_12",
                                 "Scale", "Normality"))) %>% 
  
  ggplot(aes(x = value, y = 0)) +
  stat_wilke(normalize = "panels") +
  scale_y_continuous(NULL, breaks = NULL) +
  xlab(NULL) +
  coord_cartesian(ylim = c(-0.01, NA)) +
  panel_border() +
  theme(axis.text.x = element_text(size = 10),
        legend.position = c(.74, .09)) +
  facet_wrap(~ key, scales = "free", ncol = 3)
```

<img src="18_files/figure-html/unnamed-chunk-64-1.png" width="576" style="display: block; margin: auto;" />

Based on the distributions for the random predictors, it looks like our **brms** horseshoe prior regularized more aggressively than Kruschke's hierarchical prior in the text. And interestingly, look how our marginal posterior for `Spend` is bimodal.

For kicks and giggles, here's the corresponding coefficient plot for $\beta_1$ through $\beta_{14}$.


```r
post %>% 
  select(Spend:x_rand_12) %>% 
  gather() %>% 
  
  ggplot(aes(x = value, y = reorder(key, value))) +
  geom_vline(xintercept = 0, color = "grey25", linetype = 2) +
  stat_pointinterval(point_interval = mode_hdi, .width = .95, point_size = 4,
                     color = "steelblue4", point_color = "chocolate3") +
  labs(x = NULL,
       y = NULL) +
  theme(axis.text.y  = element_text(hjust = 0))
```

<img src="18_files/figure-html/unnamed-chunk-65-1.png" width="768" style="display: block; margin: auto;" />

But anyways, here's that final Bayesian $R^2$ density for Figure 18.12.


```r
bayes_R2(fit18.5, summary = F) %>% 
  as_tibble() %>% 
  
  ggplot(aes(x = R2, y = 0)) +
  stat_wilke() +
  scale_y_continuous(NULL, breaks = NULL) +
  labs(subtitle = expression(paste("Bayesian ", italic(R)^2)),
       x = NULL) +
  coord_cartesian(xlim = c(0, 1),
                  ylim = c(-0.01, NA)) +
  theme(legend.position = c(.01, .8))
```

<img src="18_files/figure-html/unnamed-chunk-66-1.png" width="336" style="display: block; margin: auto;" />

Just recall, though, that our `fit18.5` was not exactly like Kruschke's model. Whereas we hard coded the scale of our Student-$t$ horseshoe prior to be 1, Kruschke estimated it with help from the gamma distribution. I'm not aware that's currently possible in **brms**. If I'm at fault and you know how to do it, [please share your code](https://github.com/ASKurz/Doing-Bayesian-Data-Analysis-in-brms-and-the-tidyverse/issues).

## Variable selection

We can rewrite the linear regression model to accommodate whether it includes a predictor as

$$\mu_i = \beta_0 + \sum_j \delta_j \beta_j x_{j, i},$$

where $\delta$ is a dummy for which 0 = *not included* 1 = *included*. I'm not aware of a way to use $\delta$ as an inclusion indicator in **brms** the way Kruschke implemented it in JAGS. And in fact, it appears this might be [unfeasible within the Stan framework](https://discourse.mc-stan.org/t/include-extra-coefficient-multiplied-with-regression-weight-inclusion-weight-a-la-kruschke/5768). But if you know of a way, please [share your code](https://github.com/ASKurz/Doing-Bayesian-Data-Analysis-in-brms-and-the-tidyverse/issues). However, this issue can lead to a similar approach: information criteria. To do so, let's follow Kruschke's basic flow and use the first model from way back in [Section 18.1.1][The perils of correlated predictors.] as a starting point. The model formula was as follows.


```r
fit18.1$formula
```

```
## satt_z ~ 1 + spend_z + prcnt_take_z
```

Taking interactions off the table for a moment, we can specify four model types with various combinations of the two predictors, `prcnt_take_z` and `spend_z`. `fit18.1` was the first, which we might denote as $\langle 1, 1 \rangle$. That leads to the remaining possibilities as

* $\langle 1, 0 \rangle:$ `satt_z ~ 1 + spend_z`
* $\langle 0, 1 \rangle:$ `satt_z ~ 1 + prcnt_take_z`
* $\langle 0, 0 \rangle:$ `satt_z ~ 1`

Let's fit those models.


```r
fit18.6 <-
  update(fit18.1,
         formula = satt_z ~ 1 + spend_z,
         seed = 18,
         file = "fits/fit18.06")

fit18.7 <-
  update(fit18.1,
         formula = satt_z ~ 1 + prcnt_take_z,
         seed = 18,
         file = "fits/fit18.07")

fit18.8 <-
  brm(data = my_data,
      family = student,
      satt_z ~ 1,
      prior = c(prior(normal(0, 2), class = Intercept),
                prior(normal(0, 1), class = sigma),
                prior(exponential(one_over_twentynine), class = nu)),
      chains = 4, cores = 4,
      stanvars = stanvar(1/29, name = "one_over_twentynine"),
      seed = 18,
      file = "fits/fit18.08")
```

We'll compare our models with the LOO information criterion. Like other information criteria, the LOO values aren't of interest in and of themselves. However, the values of one model's LOO relative to that of another is of great interest. We generally prefer models with lower estimates.


```r
fit18.1 <- add_criterion(fit18.1, "loo")
fit18.6 <- add_criterion(fit18.6, "loo")
fit18.7 <- add_criterion(fit18.7, "loo")
fit18.8 <- add_criterion(fit18.8, "loo")

loo_compare(fit18.1, fit18.6, fit18.7, fit18.8) %>% 
  print(simplify = F)
```

```
##         elpd_diff se_diff elpd_loo se_elpd_loo p_loo se_p_loo looic se_looic
## fit18.1   0.0       0.0   -31.9      5.4         4.0   0.7     63.8  10.8   
## fit18.7  -3.2       2.9   -35.2      4.4         2.7   0.5     70.3   8.8   
## fit18.6 -37.7       6.4   -69.6      4.0         2.2   0.3    139.3   8.1   
## fit18.8 -40.8       5.8   -72.7      3.1         1.4   0.2    145.5   6.1
```

In this case, `fit18.1` and `fit18.7` clearly have the lowest estimates, but the standard error of their difference score is about the same size as their difference. So the LOO difference score puts them on similar footing. Recall that you can do a similar analysis with the `waic()` function.

Let's compare that with the insights from the `model_weights()` function.


```r
(mw <- model_weights(fit18.1, fit18.6, fit18.7, fit18.8))
```

```
##      fit18.1      fit18.6      fit18.7      fit18.8 
## 8.872838e-01 3.932487e-07 1.127158e-01 4.366705e-08
```

If you don't like scientific notation, you can always wrangle and plot.


```r
mw %>% 
  as.data.frame() %>% 
  rownames_to_column() %>% 
  set_names("fit", "estimate") %>% 
  
  ggplot(aes(x = estimate, y = reorder(fit, estimate))) +
  geom_text(aes(label = estimate %>% round(3) %>% as.character())) +
  scale_x_continuous("stacking weight", limits = c(0, 1)) +
  ylab(NULL)
```

<img src="18_files/figure-html/unnamed-chunk-70-1.png" width="576" style="display: block; margin: auto;" />

Based on this weighting scheme, almost all the weight went to the full model, `fit18.1`. But note, in the intro of their [vignette on the topic](https://CRAN.R-project.org/package=loo/vignettes/loo2-weights.html), @vehtariBayesianStackingPseudoBMA opined:

> Ideally, we would avoid the Bayesian model combination problem by extending the model to include the separate models as special cases, and preferably as a continuous expansion of the model space. For example, instead of model averaging over different covariate combinations, all potentially relevant covariates should be included in a predictive model (for causal analysis more care is needed) and a prior assumption that only some of the covariates are relevant can be presented with regularized horseshoe prior [@piironenSparsityInformationRegularization2017]. For variable selection we recommend projective predictive variable selection (Piironen and Vehtari, 2017; [projpred package](https://CRAN.R-project.org/package=projpred)).

Perhaps unsurprisingly, their thoughts on the topic are similar with the [Gelman et al](https://stat.columbia.edu/~gelman/book/) quotation Kruschke provided on page 536:

> Some prominent authors eschew the variable-selection approach for typical applications in their fields. For example, [@gelman2013bayesian, p. 369] said, "For the regressions we typically see, we do not believe any coefficients to be truly zero and we do not generally consider it a conceptual (as opposed to computational) advantage to get point estimates of zero—but regularized estimates such as obtained by lasso can be much better than those resulting from simple least squares and flat prior distributions ...we are not comfortable with an underlying model in which the coefficients can be exactly zero."

For more on some of these methods, check out Vehtari's GitHub repository, [Tutorial on model assessment, model selection and inference after model selection](https://github.com/avehtari/modelselection).

But anyways, our model weighting methods cohered with Kruschke's $\delta$-inclusion-indicator method in that both suggested the full model, `fit1`, and the model with `prcnt_take` as the sole predictor, `fit7`, were given the greatest weight. I'm not aware that our information criteria weighting/model stacking methods provide probability distributions of the type Kruschke displayed in the left portions of Figure 18.13. But we can at least recreate the plots in the other panels.


```r
# first we'll get the posterior draws from `fit18.1` and wrangle them
posterior_samples(fit18.1) %>% 
  transmute(Spend     = make_beta_j(zeta_j = b_spend_z,
                                    sd_j   = sd_x_1,
                                    sd_y   = sd_y),
            PrcntTake = make_beta_j(zeta_j = b_prcnt_take_z,
                                    sd_j   = sd_x_2,
                                    sd_y   = sd_y)) %>% 
  gather() %>% 
  # within `bind_rows()`, we extract and wrangle the posterior draws from `fit18.7` and them insert them below those from `fit18.1`
  bind_rows(
    posterior_samples(fit18.7) %>%
      transmute(value = make_beta_j(zeta_j = b_prcnt_take_z,
                                    sd_j   = sd_x_2,
                                    sd_y   = sd_y)) %>% 
      mutate(key = "PrcntTake")
  ) %>% 
  # now we just need a little indexing and factor ordering
  mutate(model = rep(c("fit18.1", "fit18.7"), times = c(8000, 4000)), 
         key   = factor(key, levels = c("Spend", "PrcntTake"))) %>% 
  
  # we finally plot!
  ggplot(aes(x = value, y = 0)) +
  stat_wilke(normalize = "panels") +
  scale_y_continuous(NULL, breaks = NULL) +
  xlab(NULL) +
  coord_cartesian(ylim = c(-0.01, NA)) +
  panel_border() +
  theme(legend.position = c(.13, .23)) +
  facet_grid(model ~ key, scales = "free")
```

<img src="18_files/figure-html/unnamed-chunk-71-1.png" width="576" style="display: block; margin: auto;" />

### Inclusion probability is strongly affected by vagueness of prior.

To follow along, let's fit the models with the updated $SD = 1$ on the $\beta_{1+}$ priors code.


```r
fit18.9 <-
  update(fit18.1,
         prior = c(prior(normal(0, 1), class = Intercept),
                   prior(normal(0, 1), class = b),
                   prior(normal(0, 1), class = sigma),
                   prior(exponential(one_over_twentynine), class = nu)),
         chains = 4, cores = 4,
         stanvars = stanvar(1/29, name = "one_over_twentynine"),
         seed = 18,
         file = "fits/fit18.09")

fit18.10 <-
  update(fit18.9,
         formula = satt_z ~ 1 + spend_z,
         seed = 18,
         file = "fits/fit18.10")

fit18.11 <-
  update(fit18.9,
         formula = satt_z ~ 1 + prcnt_take_z,
         seed = 18,
         file = "fits/fit18.11")

fit18.12 <-
  update(fit18.8,
         prior = c(prior(normal(0, 1), class = Intercept),
                   prior(normal(0, 1), class = sigma),
                   prior(exponential(one_over_twentynine), class = nu)),
         seed = 18,
         file = "fits/fit18.12")
```

And now we'll fit the models with the updated $SD = 10$.


```r
fit18.13 <-
  update(fit18.9,
         prior = c(prior(normal(0, 10), class = Intercept),
                   prior(normal(0, 10), class = b),
                   prior(normal(0, 10), class = sigma),
                   prior(exponential(one_over_twentynine), class = nu)),
         seed = 18,
         file = "fits/fit18.13")

fit18.14 <-
  update(fit18.13,
         formula = satt_z ~ 1 + spend_z,
         seed = 18,
         file = "fits/fit18.14")

fit18.15 <-
  update(fit18.13,
         formula = satt_z ~ 1 + prcnt_take_z,
         seed = 18,
         file = "fits/fit18.15")

fit18.16 <-
  update(fit18.12,
         prior = c(prior(normal(0, 10), class = Intercept),
                   prior(normal(0, 10), class = sigma),
                   prior(exponential(one_over_twentynine), class = nu)),
         seed = 18,
         file = "fits/fit18.16")
```

Now we've fit the models, we're ready to examine how altering the $SD$s on the $\beta_j$ priors influenced the model comparisons via `model_weights()`. Here we'll use the default stacking method.


```r
mw %>% 
  rbind(model_weights(fit18.9, fit18.10, fit18.11, fit18.12),
        model_weights(fit18.13, fit18.14, fit18.15, fit18.16)) %>% 
  as_tibble() %>% 
  set_names("1, 1", "1, 0", "0, 1", "0, 0") %>% 
  gather() %>% 
  mutate(prior = rep(str_c("SD = ", c(10, 2, 1)), times = 4) %>% 
           factor(., levels = str_c("SD = ", c(10, 2, 1)))) %>% 
  
  ggplot(aes(x = value, y = reorder(key, value))) +
  geom_text(aes(label = value %>% round(3) %>% as.character())) +
  labs(x = "Stacking weight",
       y = expression(paste("Models defined by Kruschke's ", delta, " notation"))) +
  coord_cartesian(xlim = c(0, 1)) +
  theme(panel.grid = element_blank()) +
  panel_border() +
  facet_grid(prior ~ .)
```

<img src="18_files/figure-html/unnamed-chunk-72-1.png" width="576" style="display: block; margin: auto;" />

So unlike in the depictions in Figure 18.14, the stacking method was *insensitive* to the $SD$s on our $\beta_j$ priors. We might compare LOO difference scores, too.


```r
fit18.9  <- add_criterion(fit18.9,  "loo")
fit18.10 <- add_criterion(fit18.10, "loo")
fit18.11 <- add_criterion(fit18.11, "loo")
fit18.12 <- add_criterion(fit18.12, "loo")

fit18.13 <- add_criterion(fit18.13, "loo")
fit18.14 <- add_criterion(fit18.14, "loo")
fit18.15 <- add_criterion(fit18.15, "loo")
fit18.16 <- add_criterion(fit18.16, "loo")

loo_compare(fit18.1, fit18.6, fit18.7, fit18.8) %>% 
  print(simplify = F)
```

```
##         elpd_diff se_diff elpd_loo se_elpd_loo p_loo se_p_loo looic se_looic
## fit18.1   0.0       0.0   -31.9      5.4         4.0   0.7     63.8  10.8   
## fit18.7  -3.2       2.9   -35.2      4.4         2.7   0.5     70.3   8.8   
## fit18.6 -37.7       6.4   -69.6      4.0         2.2   0.3    139.3   8.1   
## fit18.8 -40.8       5.8   -72.7      3.1         1.4   0.2    145.5   6.1
```

```r
loo_compare(fit18.9, fit18.10, fit18.11, fit18.12) %>% 
  print(simplify = F)
```

```
##          elpd_diff se_diff elpd_loo se_elpd_loo p_loo se_p_loo looic se_looic
## fit18.9    0.0       0.0   -32.1      5.4         4.1   0.8     64.1  10.7   
## fit18.11  -3.1       2.8   -35.2      4.4         2.7   0.5     70.3   8.8   
## fit18.10 -37.5       6.3   -69.5      4.0         2.1   0.3    139.1   8.1   
## fit18.12 -40.6       5.7   -72.7      3.0         1.3   0.2    145.4   6.1
```

```r
loo_compare(fit18.13, fit18.14, fit18.15, fit18.16) %>% 
  print(simplify = F)
```

```
##          elpd_diff se_diff elpd_loo se_elpd_loo p_loo se_p_loo looic se_looic
## fit18.13   0.0       0.0   -31.9      5.3         3.9   0.7     63.7  10.7   
## fit18.15  -3.3       2.8   -35.2      4.4         2.8   0.5     70.4   8.7   
## fit18.14 -37.8       6.3   -69.7      4.0         2.1   0.3    139.4   7.9   
## fit18.16 -40.9       5.7   -72.8      3.0         1.3   0.2    145.6   6.0
```

The LOO difference score patterns were also about the same across the $SD$s on our $\beta_j$ priors. Let's finish up with our version of the histograms comparing the model predictors. Here's the code for those in the top portion of Figure 18.14.


```r
# first we'll get the posterior draws from `fit18.9` and wrangle them
posterior_samples(fit18.9) %>% 
  transmute(Spend     = make_beta_j(zeta_j = b_spend_z,
                                    sd_j   = sd_x_1,
                                    sd_y   = sd_y),
            PrcntTake = make_beta_j(zeta_j = b_prcnt_take_z,
                                    sd_j   = sd_x_2,
                                    sd_y   = sd_y)) %>% 
  gather() %>% 
  # within `bind_rows()`, we extract and wrangle the posterior draws from `fit18.11` and 
  # then insert them below those from `fit18.9`
  bind_rows(
    posterior_samples(fit18.11) %>% 
      transmute(value = make_beta_j(zeta_j = b_prcnt_take_z,
                                    sd_j   = sd_x_2,
                                    sd_y   = sd_y)) %>% 
      mutate(key = "PrcntTake")
  ) %>% 
  # now we just need a little indexing and factor ordering
  mutate(model = rep(c("fit18.9", "fit18.11"), times = c(8000, 4000)) %>% 
           factor(., levels = c("fit18.9", "fit18.11")),
         key   = factor(key, levels = c("Spend", "PrcntTake"))) %>%
  
  # we finally plot!
  ggplot(aes(x = value, y = 0)) +
  stat_wilke(normalize = "panels") +
  scale_y_continuous(NULL, breaks = NULL) +
  xlab(NULL) +
  coord_cartesian(ylim = c(-0.01, NA)) +
  panel_border() +
  theme(legend.position = c(.13, .23)) +
  facet_grid(model ~ key, scales = "free")
```

<img src="18_files/figure-html/unnamed-chunk-73-1.png" width="576" style="display: block; margin: auto;" />

And now we'll do our version of the histograms for the bottom portion of Figure 18.14.


```r
posterior_samples(fit18.13) %>% 
  transmute(Spend     = make_beta_j(zeta_j = b_spend_z,
                                    sd_j   = sd_x_1,
                                    sd_y   = sd_y),
            PrcntTake = make_beta_j(zeta_j = b_prcnt_take_z,
                                    sd_j   = sd_x_2,
                                    sd_y   = sd_y)) %>% 
  gather() %>% 
  bind_rows(
    posterior_samples(fit18.15) %>% 
      transmute(value = make_beta_j(zeta_j = b_prcnt_take_z,
                                    sd_j   = sd_x_2,
                                    sd_y   = sd_y)) %>% 
      mutate(key = "PrcntTake")
  ) %>% 
  mutate(model = rep(c("fit18.13", "fit18.15"), times = c(8000, 4000)) %>% 
           factor(., levels = c("fit18.13", "fit18.15")),
         key   = factor(key, levels = c("Spend", "PrcntTake"))) %>%
  
  ggplot(aes(x = value, y = 0)) +
  stat_wilke(normalize = "panels") +
  scale_y_continuous(NULL, breaks = NULL) +
  xlab(NULL) +
  coord_cartesian(ylim = c(-0.01, NA)) +
  theme(legend.position = c(.13, .23)) +
  panel_border() +
  facet_grid(model ~ key, scales = "free")
```

<img src="18_files/figure-html/unnamed-chunk-74-1.png" width="576" style="display: block; margin: auto;" />

Kruschke concluded this subsection with

> Bayesian model comparison can be strongly affected by the degree of vagueness in the priors, even though explicit estimates of the parameter values may be minimally affected. Therefore, be very cautious when interpreting the results of Bayesian variable selection. The next section discusses a way to inform the prior by using concurrent data instead of previous data. (p. 542)

We should note that while the method in text was "strongly affected by the degree of vagueness in the priors", the information-criteria and model weighting methods, above, were not. If you're interested in comparing models within the Bayesian paradigm, choose your method with care.

### Variable selection with hierarchical shrinkage.

Kruschke opened the subsection with a few good points:

> If you have strong previous research that can inform the prior, then it should be used. But if previous knowledge is weak, then the uncertainty should be expressed in the prior. This is an underlying mantra of the Bayesian approach: Any uncertainty should be expressed in the prior. (p. 543)

Here we'll standardize our new predictors, `StuTeaRat` and `Salary`.


```r
my_data <-
  my_data %>% 
  mutate(stu_tea_rat_z = standardize(StuTeaRat),
         salary_z      = standardize(Salary))
```

We can use Kruschke's `gamma_s_and_r_from_mode_sd()` function to return the exact shape and rate parameters to make a gamma with a mode of 1 and an $SD$ of 10.


```r
gamma_s_and_r_from_mode_sd <- function(mode, sd) {
  if (mode <= 0) stop("mode must be > 0")
  if (sd   <= 0) stop("sd must be > 0")
  rate  <- (mode + sqrt(mode^2 + 4 * sd^2)) / (2 * sd^2)
  shape <- 1 + mode * rate
  return(list(shape = shape, rate = rate))
}
```

Here are the values.


```r
(p <- gamma_s_and_r_from_mode_sd(mode = 1, sd = 10) %>% as.numeric())
```

```
## [1] 1.1051249 0.1051249
```

That gamma distribution looks like this.


```r
tibble(x = seq(from = 0, to = 65, length.out = 1e3)) %>% 
  ggplot(aes(x = x, y = dgamma(x, p[1], p[2]))) +
  geom_area(color = "steelblue4", fill = "steelblue4", alpha = .6) +
  scale_y_continuous(NULL, breaks = NULL) +
  xlab("Our gamma prior") +
  coord_cartesian(xlim = c(0, 60))
```

<img src="18_files/figure-html/unnamed-chunk-78-1.png" width="384" style="display: block; margin: auto;" />

We can code those values in with arbitrary precision with the `stanvar()` function.


```r
stanvars <- 
  stanvar(1/29, name = "one_over_twentynine") +
  stanvar(p[1], name = "my_shape") +
  stanvar(p[2], name = "my_rate") +
  stanvar(scode = "  real<lower=0> tau;", block = "parameters")
```

Note that last `stanvar()` line. Bürkner recently posted an [exemplar of how to set a hierarchical prior on a regression coefficient](https://github.com/paul-buerkner/brms/issues/459) in a `brm()` model:


```r
# define a hierarchical prior on the regression coefficients
bprior <- set_prior("normal(0, tau)", class = "b") +
  set_prior("target += normal_lpdf(tau | 0, 10)", check = FALSE)

stanvars <- stanvar(scode = "  real<lower=0> tau;", block = "parameters")

make_stancode(count ~ Trt + log_Base4_c, epilepsy,
              prior = bprior, stanvars = stanvars)
```

Following the method, we tell `brm()` we'd like to estimate the $SD$ of our $\beta_{1+}$ priors with `prior(normal(0, tau), class = b)`, where the `tau` is a stand-in for the $SD$. In the next line, `set_prior("target += gamma_lpdf(tau | my_shape, my_rate)", check = FALSE)`, we tell `brm()` we'd like to estimate `tau` with a gamma(`my_shape`, `my_rate`), the values for which were saved in our `stanvars` object, above. And it's that `stanvar()` line in that code wherein we told `brm()` we'd like that parameter to have a lower bound of 0. Let's put it to use.


```r
fit18.1111 <-
  brm(data = my_data,
      family = student,
      satt_z ~ 1 + spend_z + prcnt_take_z + stu_tea_rat_z + salary_z,
      prior = c(prior(normal(0, 2), class = Intercept),
                prior(normal(0, tau), class = b),
                set_prior("target += gamma_lpdf(tau | my_shape, my_rate)", check = FALSE),
                prior(normal(0, 1), class = sigma),
                prior(exponential(one_over_twentynine), class = nu)),
      chains = 4, cores = 4,
      control = list(adapt_delta = .99),
      stanvars = stanvars,
      seed = 18,
      file = "fits/fit18.1111")

fit18.0111 <-
  update(fit18.1111,
         formula = satt_z ~ 1           + prcnt_take_z + stu_tea_rat_z + salary_z,
         file = "fits/fit18.0111")

fit18.1011 <-
  update(fit18.1111,
         formula = satt_z ~ 1 + spend_z                + stu_tea_rat_z + salary_z,
         file = "fits/fit18.1011")
 
fit18.1101 <-
  update(fit18.1111,
         formula = satt_z ~ 1 + spend_z + prcnt_take_z                 + salary_z,
         file = "fits/fit18.1101")

fit18.1110 <-
  update(fit18.1111,
         formula = satt_z ~ 1 + spend_z + prcnt_take_z + stu_tea_rat_z           ,
         file = "fits/fit18.1110")

fit18.0011 <-
  update(fit18.1111,
         formula = satt_z ~ 1                          + stu_tea_rat_z + salary_z,
         file = "fits/fit18.0011")

fit18.0101 <-
  update(fit18.1111,
         formula = satt_z ~ 1           + prcnt_take_z                 + salary_z,
         file = "fits/fit18.0101")

fit18.0110 <-
  update(fit18.1111,
         formula = satt_z ~ 1           + prcnt_take_z + stu_tea_rat_z           ,
         file = "fits/fit18.0110")

fit18.1001 <-
  update(fit18.1111,
         formula = satt_z ~ 1 + spend_z                                + salary_z,
         file = "fits/fit18.1001")

fit18.1010 <-
  update(fit18.1111,
         formula = satt_z ~ 1 + spend_z                + stu_tea_rat_z           ,
         file = "fits/fit18.1010")

fit18.1100 <-
  update(fit18.1111,
         formula = satt_z ~ 1 + spend_z + prcnt_take_z                           ,
         file = "fits/fit18.1100")

fit18.0001 <-
  update(fit18.1111,
         formula = satt_z ~ 1                                          + salary_z,
         file = "fits/fit18.0001")

fit18.0010 <-
  update(fit18.1111,
         formula = satt_z ~ 1                          + stu_tea_rat_z           ,
         file = "fits/fit18.0010")

fit18.0100 <-
  update(fit18.1111,
         formula = satt_z ~ 1           + prcnt_take_z                           ,
         file = "fits/fit18.0100")

fit18.1000 <-
  update(fit18.1111,
         formula = satt_z ~ 1 + spend_z                                          ,
         file = "fits/fit18.1000")

fit18.0000 <-
  update(fit18.1111,
         formula = satt_z ~ 1                                                    ,
         file = "fits/fit18.0000")
```

In order to keep track of the next 16 models, we switched our usual naming convention. Instead of continuing on keeping on calling them `fit18.17` through `fit18.33`, we used Kruschke's $\delta$ 0/1 convention. If we set the formula for the full model as `satt_z ~ 1 + spend_z + prcnt_take_z + stu_tea_rat_z + salary_z`, the name becomes `fit18.1111`. Accordingly, we called the model omitting `spend_z`, the first predictor, `fit18.0111`, and so on.

Before we go any further, here are the correlations among the $\beta$'s for the full model, `fit18.1111`.


```r
vcov(fit18.1111, correlation = T) %>% 
  round(digits = 3)
```

```
##               Intercept spend_z prcnt_take_z stu_tea_rat_z salary_z
## Intercept         1.000  -0.019        0.006         0.008    0.012
## spend_z          -0.019   1.000        0.074         0.709   -0.895
## prcnt_take_z      0.006   0.074        1.000         0.262   -0.353
## stu_tea_rat_z     0.008   0.709        0.262         1.000   -0.697
## salary_z          0.012  -0.895       -0.353        -0.697    1.000
```

Once again, the HMC correlations differ from Kruschke's JAGS correlations. Moving on--behold the model weights.


```r
(
  mw <-
  model_weights(fit18.1111, 
                fit18.0111, fit18.1011, fit18.1101, fit18.1110,
                fit18.0011, fit18.0101, fit18.0110, fit18.1001, fit18.1010, fit18.1100, 
                fit18.0001, fit18.0010, fit18.0100, fit18.1000,
                fit18.0000)
 )
```

```
##   fit18.1111   fit18.0111   fit18.1011   fit18.1101   fit18.1110   fit18.0011 
## 1.542787e-03 2.333720e-01 8.266284e-07 1.730662e-06 2.352893e-04 6.846063e-05 
##   fit18.0101   fit18.0110   fit18.1001   fit18.1010   fit18.1100   fit18.0001 
## 3.196282e-02 2.403752e-02 1.632842e-06 2.490547e-05 2.012877e-01 1.303326e-01 
##   fit18.0010   fit18.0100   fit18.1000   fit18.0000 
## 6.931957e-07 2.962150e-01 8.091606e-02 9.974978e-09
```

We'll plot our model weights like before.


```r
mw %>% 
  as.data.frame() %>% 
  rownames_to_column() %>% 
  set_names("fit", "weight") %>% 
  mutate(fit = str_remove(fit, "fit18.")) %>% 
  
  ggplot(aes(x = weight, y = reorder(fit, weight))) +
  geom_text(aes(label = weight %>% round(3) %>% as.character()),
            size = 3) +
  coord_cartesian(xlim = c(0, 1)) +
  labs(x = "Stacking weight",
       y = "fit18.[xxxx]") +
  theme(panel.grid = element_blank()) +
  panel_border()
```

<img src="18_files/figure-html/unnamed-chunk-82-1.png" width="576" style="display: block; margin: auto;" />

As you might notice, pattern among model weights is similar with but not identical to the one among the model probabilities Kruschke displayed in Figure 18.15. Here we'll plot the histograms for our top six.


```r
# first, we need to redefine `sd_x_3` and `sd_x_4` in terms of our two new predictors
sd_x_3 <- sd(my_data$StuTeaRat)
sd_x_4 <- sd(my_data$Salary)

## Now we'll start extracting our posterior samples and wrangling them, by model
# fit18.0100
posterior_samples(fit18.0100) %>% 
  transmute(PrcntTake = make_beta_j(zeta_j = b_prcnt_take_z,
                                    sd_j   = sd_x_2,
                                    sd_y   = sd_y)) %>% 
  gather() %>% 
  mutate(fit = "fit18.0100") %>% 
  # fit18.0111
  bind_rows(
    posterior_samples(fit18.0111) %>% 
      transmute(PrcntTake = make_beta_j(zeta_j = b_prcnt_take_z,
                                        sd_j   = sd_x_2,
                                        sd_y   = sd_y),
                StuTeaRat = make_beta_j(zeta_j = b_stu_tea_rat_z,
                                        sd_j   = sd_x_3,
                                        sd_y   = sd_y),
                Salary    = make_beta_j(zeta_j = b_salary_z,
                                        sd_j   = sd_x_4,
                                        sd_y   = sd_y)) %>% 
      gather() %>% 
      mutate(fit = "fit18.0111")
    )  %>% 
  # fit18.1100
  bind_rows(
    posterior_samples(fit18.1100) %>% 
      transmute(Spend     = make_beta_j(zeta_j = b_spend_z,
                                        sd_j   = sd_x_1,
                                        sd_y   = sd_y),
                PrcntTake = make_beta_j(zeta_j = b_prcnt_take_z,
                                        sd_j   = sd_x_2,
                                        sd_y   = sd_y)) %>% 
      gather() %>% 
      mutate(fit = "fit18.1100")
    )  %>% 
  # fit18.0001
  bind_rows(
    posterior_samples(fit18.0001) %>% 
      transmute(Salary    = make_beta_j(zeta_j = b_salary_z,
                                        sd_j   = sd_x_4,
                                        sd_y   = sd_y)) %>% 
      gather() %>% 
      mutate(fit = "fit18.0001")
    )  %>% 
  # fit18.1000
  bind_rows(
    posterior_samples(fit18.1000) %>% 
      transmute(Spend     = make_beta_j(zeta_j = b_spend_z,
                                        sd_j   = sd_x_1,
                                        sd_y   = sd_y)) %>% 
      gather() %>% 
      mutate(fit = "fit18.1000")
    )  %>% 
  # fit18.0110       # spend_z + prcnt_take_z + stu_tea_rat_z
  bind_rows(
    posterior_samples(fit18.0110) %>% 
      transmute(PrcntTake = make_beta_j(zeta_j = b_prcnt_take_z,
                                        sd_j   = sd_x_2,
                                        sd_y   = sd_y),
                StuTeaRat = make_beta_j(zeta_j = b_stu_tea_rat_z,
                                        sd_j   = sd_x_3,
                                        sd_y   = sd_y)) %>% 
      gather() %>% 
      mutate(fit = "fit18.0110")
    ) %>% 
  # the next two lines just help order the grid the plots appear in
  mutate(key = factor(key, levels = c("Spend", "PrcntTake", "StuTeaRat", "Salary")),
         fit = factor(fit, levels = c("fit18.0100", "fit18.0111", "fit18.1100", "fit18.0001", "fit18.1000", "fit18.0110"))) %>%
  
  # finally, the plot!
  ggplot(aes(x = value, y = 0)) +
  stat_wilke(normalize = "panels", point_size = 4) +
  scale_fill_viridis_d(option = "D", begin = .2, end = .8) +
  scale_y_continuous(NULL, breaks = NULL) +
  xlab(NULL) +
  coord_cartesian(ylim = c(-0.01, NA)) +
  panel_border() +
  theme(legend.position = "none") +
  facet_grid(fit ~ key, scales = "free")
```

<img src="18_files/figure-html/unnamed-chunk-83-1.png" width="672" style="display: block; margin: auto;" />

Like Kruschke's results in the text, `PrcntTake` was the most prominent predictor.

### What to report and what to conclude.

Kruschke made a great point in the opening paragraph of this subsection.

> It might make sense to use the single most credible model, especially if it is notably more credible than the runner up, and if the goal is to have a parsimonious explanatory description of the data. But it is important to recognize that using the single best model, when it excludes some predictors, is concluding that the regression coefficients on the excluded predictors are exactly zero. (p. 546)

Later he added "A forthright report should state the posterior probabilities of the several top models. Additionally, it can be useful to report, for each model, the ratio of its posterior probability relative to that of the best model" (p. 546). With our information criteria and model weights approach, we don't have posterior probabilities for the models themselves. But we can report on their information criteria comparisons and weights.

In the final paragraph of the subsection, Kruschke wrote:

> When the goal is prediction of $y$ for interesting values of the predictors, as opposed to parsimonious explanation, then it is usually not appropriate to use only the single most probable model. Instead, predictions should be based on as much information as possible, using all models to the extent that they are credible. This approach is called Bayesian model averaging (BMA). (p. 547)

It's worth it to walk this out a bit. With **brms**, one can use `brms::pp_average()` to get the weighted posterior distributions for the model parameters. This is a natural extension of our model weights comparisons.


```r
# how many points on the x-axis?
n_points <- 30

# what vales of the predictors would we like to evaluate the weighted posterior over?
nd <-
  tibble(spend_z       = seq(from = -3, to = 3, length.out = n_points),
         prcnt_take_z  = 0, 
         stu_tea_rat_z = 0, 
         salary_z      = 0)

pp <-
  # the first things we feed into `pp_average()` are the `brm()` fits we'd like to average over
  pp_average(fit18.1111, fit18.0111, fit18.1011, fit18.1101, fit18.1110, fit18.0011, fit18.0101, fit18.0110, fit18.1001, fit18.1010, fit18.1100, fit18.0001, fit18.0010, fit18.0100, fit18.1000, fit18.0000,
             # here we tell it to evaluate the posterior over these predictor values
             newdata = nd, 
             # we can get the mean trends using the "fitted" method
             method = "fitted",
             # by `robust`, we mean we'd like the Estimate in terms of posterior medians, rather than means
             robust = T)

str(pp)
```

```
##  num [1:30, 1:4] -0.0166 -0.0166 -0.0166 -0.0166 -0.0166 ...
##  - attr(*, "dimnames")=List of 2
##   ..$ : NULL
##   ..$ : chr [1:4] "Estimate" "Est.Error" "Q2.5" "Q97.5"
##  - attr(*, "weights")= Named num [1:16] 1.54e-03 2.33e-01 8.27e-07 1.73e-06 2.35e-04 ...
##   ..- attr(*, "names")= chr [1:16] "fit18.1111" "fit18.0111" "fit18.1011" "fit18.1101" ...
##  - attr(*, "nsamples")= Named num [1:16] 6 934 0 0 1 0 128 96 0 0 ...
##   ..- attr(*, "names")= chr [1:16] "fit18.1111" "fit18.0111" "fit18.1011" "fit18.1101" ...
```

The `pp` object will require a little wrangling before it's of use for **ggplot2**.


```r
pp %>% 
  as_tibble() %>%
  bind_cols(nd) %>% 

  ggplot(aes(x = spend_z, y = Estimate,
             ymin = Q2.5, ymax = Q97.5)) +
  geom_hline(yintercept = 0, color = "grey25", linetype = 2) +
  geom_pointrange(shape = 21, stroke = 1/10, fatten = 6, 
                  color = "steelblue4", fill = "chocolate3") +
  labs(x = "Value of Spend_z",
       y = "Standardized SATT")
```

<img src="18_files/figure-html/unnamed-chunk-84-1.png" width="576" style="display: block; margin: auto;" />

We can build on this to make a plot considering each of the four predictors. But first that requires we make a new `nd` tibble to feed into `pp_average()`.


```r
# how many points on the x-axis?
n_points <- 30

# what vales of the predictors would we like to evaluate the weighted posterior over?
nd <-
  tibble(spend_z       = c(seq(from = -3, to = 3, length.out = n_points),
                           rep(0, times = n_points * 3)),
         
         prcnt_take_z  = c(rep(0, times = n_points),
                           seq(from = -3, to = 3, length.out = n_points),
                           rep(0, times = n_points * 2)), 
         
         stu_tea_rat_z = c(rep(0, times = n_points * 2),
                           seq(from = -3, to = 3, length.out = n_points),
                           rep(0, times = n_points)), 
         
         salary_z      = c(rep(0, times = n_points * 3),
                           seq(from = -3, to = 3, length.out = n_points)))

pp <-
  pp_average(fit18.1111, fit18.0111, fit18.1011, fit18.1101, fit18.1110, fit18.0011, fit18.0101, fit18.0110, fit18.1001, fit18.1010, fit18.1100, fit18.0001, fit18.0010, fit18.0100, fit18.1000, fit18.0000,
             newdata = nd, 
             method = "fitted",
             robust = T,
             # note the `probs` argument
             probs = c(.025, .975, .1, .9, .25, .75))

str(pp)
```

```
##  num [1:120, 1:8] -0.016 -0.0158 -0.0158 -0.0158 -0.0158 ...
##  - attr(*, "dimnames")=List of 2
##   ..$ : NULL
##   ..$ : chr [1:8] "Estimate" "Est.Error" "Q2.5" "Q97.5" ...
##  - attr(*, "weights")= Named num [1:16] 1.54e-03 2.33e-01 8.27e-07 1.73e-06 2.35e-04 ...
##   ..- attr(*, "names")= chr [1:16] "fit18.1111" "fit18.0111" "fit18.1011" "fit18.1101" ...
##  - attr(*, "nsamples")= Named num [1:16] 6 934 0 0 1 0 128 96 0 0 ...
##   ..- attr(*, "names")= chr [1:16] "fit18.1111" "fit18.0111" "fit18.1011" "fit18.1101" ...
```

In each panel of the plot, below, we focus on one predictor. For that predictor, we hold all other three at their mean, which, since they are all standardized, is zero. We consider the posterior predictions for standardized SAT scores across a range of values each focal predictor. The posterior predictions are depicted in terms of 95%, 80%, and 50% percentile-based interval bands and a line at the median.


```r
pp %>% 
  as_tibble() %>% 
  mutate(x = seq(from = -3, to = 3, length.out = n_points) %>% rep(., times = 4),
         predictor = rep(c("Spend_z", "PrcntTake_z", "StuTeaRat_z", "Salary_z"), each = n_points)) %>% 
  
  ggplot(aes(x = x)) +
  geom_hline(yintercept = 0, color = "grey25", linetype = 2) +
  geom_ribbon(aes(ymin = Q2.5, ymax = Q97.5),
              alpha = 1/5, fill = "steelblue4") +
  geom_ribbon(aes(ymin = Q10, ymax = Q90),
              alpha = 1/4, fill = "steelblue4") +
  geom_ribbon(aes(ymin = Q25, ymax = Q75),
              alpha = 1/3, fill = "steelblue4") +
  geom_line(aes(y = Estimate),
            size = 1, color = "chocolate3") +
  labs(x = "Standardized value of the focal predictor",
       y = "Standardized SATT") +
  theme_minimal_vgrid() +
  panel_border() +
  facet_grid(predictor ~ ., scales = "free")
```

<img src="18_files/figure-html/unnamed-chunk-85-1.png" width="576" style="display: block; margin: auto;" />

Based on the weighted average across the models, the `PrcntTake_z` predictor was the most potent.

### Caution: Computational methods.

> To conclude this section regarding variable selection, it is appropriate to recapitulate the considerations at the beginning of the section. Variable selection is a reasonable approach only if it is genuinely plausible and meaningful that candidate predictors have zero relation to the predicted variable. The results can be surprisingly sensitive to the seemingly innocuous choice of prior for the regression coefficients, and, of course, the prior for the inclusion probability. Because of these limitations, hierarchical shrinkage priors may be a more meaningful approach. (p. 548)

### Caution: Interaction variables.

> When interaction terms are included in a model that also has hierarchical shrinkage on regression coefficients, the interaction coefficients should not be put under the same higher-level prior distribution as the individual component coefficients, because interaction coefficients are conceptually from a different class of variables than individual components. (pp. 548--549)

## Session info {-}


```r
sessionInfo()
```

```
## R version 4.0.4 (2021-02-15)
## Platform: x86_64-apple-darwin17.0 (64-bit)
## Running under: macOS Catalina 10.15.7
## 
## Matrix products: default
## BLAS:   /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRblas.dylib
## LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib
## 
## locale:
## [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
## 
## attached base packages:
## [1] stats     graphics  grDevices utils     datasets  methods   base     
## 
## other attached packages:
##  [1] GGally_2.1.1      bayesplot_1.8.0   cowplot_1.1.1     ggdist_2.4.0.9000
##  [5] tidybayes_2.3.1   brms_2.15.0       Rcpp_1.0.6        patchwork_1.1.1  
##  [9] forcats_0.5.1     stringr_1.4.0     dplyr_1.0.5       purrr_0.3.4      
## [13] readr_1.4.0       tidyr_1.1.3       tibble_3.1.1      ggplot2_3.3.3    
## [17] tidyverse_1.3.0  
## 
## loaded via a namespace (and not attached):
##   [1] readxl_1.3.1         backports_1.2.1      plyr_1.8.6          
##   [4] igraph_1.2.6         svUnit_1.0.3         splines_4.0.4       
##   [7] crosstalk_1.1.0.1    TH.data_1.0-10       rstantools_2.1.1    
##  [10] inline_0.3.17        digest_0.6.27        htmltools_0.5.1.1   
##  [13] rsconnect_0.8.16     fansi_0.4.2          magrittr_2.0.1      
##  [16] modelr_0.1.8         RcppParallel_5.0.2   matrixStats_0.57.0  
##  [19] xts_0.12.1           sandwich_3.0-0       prettyunits_1.1.1   
##  [22] colorspace_2.0-0     rvest_0.3.6          haven_2.3.1         
##  [25] xfun_0.22            callr_3.7.0          crayon_1.4.1        
##  [28] jsonlite_1.7.2       lme4_1.1-25          survival_3.2-10     
##  [31] zoo_1.8-8            glue_1.4.2           gtable_0.3.0        
##  [34] emmeans_1.5.2-1      V8_3.4.0             distributional_0.2.2
##  [37] pkgbuild_1.2.0       rstan_2.21.2         abind_1.4-5         
##  [40] scales_1.1.1         mvtnorm_1.1-1        DBI_1.1.0           
##  [43] miniUI_0.1.1.1       xtable_1.8-4         tmvnsim_1.0-2       
##  [46] HDInterval_0.2.2     stats4_4.0.4         StanHeaders_2.21.0-7
##  [49] DT_0.16              htmlwidgets_1.5.2    httr_1.4.2          
##  [52] threejs_0.3.3        RColorBrewer_1.1-2   arrayhelpers_1.1-0  
##  [55] ellipsis_0.3.2       reshape_0.8.8        pkgconfig_2.0.3     
##  [58] loo_2.4.1            farver_2.1.0         sass_0.3.1          
##  [61] dbplyr_2.0.0         utf8_1.2.1           tidyselect_1.1.0    
##  [64] labeling_0.4.2       rlang_0.4.11         reshape2_1.4.4      
##  [67] later_1.2.0          munsell_0.5.0        cellranger_1.1.0    
##  [70] tools_4.0.4          cli_2.5.0            generics_0.1.0      
##  [73] broom_0.7.5          ggridges_0.5.3       evaluate_0.14       
##  [76] fastmap_1.1.0        processx_3.5.2       knitr_1.31          
##  [79] fs_1.5.0             nlme_3.1-152         mime_0.10           
##  [82] projpred_2.0.2       xml2_1.3.2           compiler_4.0.4      
##  [85] shinythemes_1.1.2    rstudioapi_0.13      gamm4_0.2-6         
##  [88] curl_4.3             reprex_0.3.0         statmod_1.4.35      
##  [91] bslib_0.2.4          stringi_1.5.3        highr_0.8           
##  [94] ps_1.6.0             Brobdingnag_1.2-6    lattice_0.20-41     
##  [97] Matrix_1.3-2         psych_2.1.3          nloptr_1.2.2.2      
## [100] markdown_1.1         shinyjs_2.0.0        vctrs_0.3.8         
## [103] pillar_1.6.0         lifecycle_1.0.0      jquerylib_0.1.4     
## [106] bridgesampling_1.0-0 estimability_1.3     httpuv_1.6.0        
## [109] R6_2.5.0             bookdown_0.21        promises_1.2.0.1    
## [112] gridExtra_2.3        codetools_0.2-18     boot_1.3-26         
## [115] colourpicker_1.1.0   MASS_7.3-53          gtools_3.8.2        
## [118] assertthat_0.2.1     withr_2.4.2          mnormt_2.0.2        
## [121] shinystan_2.5.0      multcomp_1.4-16      mgcv_1.8-33         
## [124] parallel_4.0.4       hms_0.5.3            grid_4.0.4          
## [127] coda_0.19-4          minqa_1.2.4          rmarkdown_2.7       
## [130] shiny_1.6.0          lubridate_1.7.9.2    base64enc_0.1-3     
## [133] dygraphs_1.1.1.6
```





## Footnote {-}

[^5]: In his [Corrigenda](https://sites.google.com/site/doingbayesiandataanalysis/corrigenda), Kruschke further clarified: "that is true only in case there is a single predictor, not for multiple predictors. The statement could have said that 'R^2 is algebraically constrained to fall between −1 and +1 in least-squares regression'. More relevantly, replace the statement with the following: 'In multiple linear regression, standardized regression coefficients tend to fall between -2 and +2 unless the predictors are very strongly correlated and have strongly opposing effects. If your data have strongly correlated predictors, consider widening the prior.'"

